// Akademi Crypto — Research Library.
//
// Distilled, in-my-own-words summaries of the per-coin research reports from
// akademicrypto.com/research (the user is a lifetime member; personal-use notes,
// not a reproduction of the source PDFs). Each report is a point-in-time deep
// dive — VALUATIONS/PRICES ARE AS OF THE REPORT DATE and will be stale now; the
// durable value is the thesis, sector/narrative, tokenomics shape, and risks.
//
// Grows toward the full 72-report catalog in batches.

export type ResearchSector =
  | "layer1"
  | "layer2"
  | "defi"
  | "ai"
  | "depin"
  | "rwa"
  | "infra"
  | "interop"
  | "oracle"
  | "gaming"
  | "payments"
  | "privacy"
  | "data"
  | "meme"
  | "macro";

export const RESEARCH_SECTORS: { key: ResearchSector; label: string; emoji: string }[] = [
  { key: "layer1", label: "Layer-1", emoji: "⛓️" },
  { key: "layer2", label: "Layer-2", emoji: "🔗" },
  { key: "defi", label: "DeFi", emoji: "🏦" },
  { key: "ai", label: "AI", emoji: "🤖" },
  { key: "depin", label: "DePIN", emoji: "📡" },
  { key: "rwa", label: "RWA / Tokenisasi", emoji: "🏛️" },
  { key: "infra", label: "Infrastruktur", emoji: "🛠️" },
  { key: "interop", label: "Interoperability", emoji: "🌉" },
  { key: "oracle", label: "Oracle", emoji: "🔮" },
  { key: "gaming", label: "Gaming / NFT", emoji: "🎮" },
  { key: "payments", label: "Payments", emoji: "💸" },
  { key: "privacy", label: "Privacy", emoji: "🕵️" },
  { key: "data", label: "Data", emoji: "📊" },
  { key: "meme", label: "Meme", emoji: "🐸" },
  { key: "macro", label: "Market Outlook", emoji: "📈" },
];

export const SECTOR_META: Record<ResearchSector, { label: string; emoji: string }> =
  Object.fromEntries(RESEARCH_SECTORS.map((s) => [s.key, { label: s.label, emoji: s.emoji }])) as Record<
    ResearchSector,
    { label: string; emoji: string }
  >;

export type ResearchCard = {
  ticker: string;
  name: string;
  slug: string; // akademicrypto.com/research/<slug>
  date: string; // report date (ISO) — data is point-in-time
  sectors: ResearchSector[];
  category: string; // AC's own label, e.g. "Altcoins Outlook · DeFi"
  rating?: string; // AC's stated stance if any (e.g. "HOLD")
  valuationAtReport?: string; // market cap at report date
  supply?: string; // circ / total / max snapshot
  extra?: { label: string; value: string }[]; // upside, float, etc.
  thesis: string; // 1–2 sentence core idea
  what: string; // what the project is
  bull: string[]; // bull case / strengths
  risks: string[]; // risks / bear case
  verdict: string; // AC's takeaway
  narratives: string[]; // narrative tags
};

// Sorted newest-first at render time.
export const RESEARCH: ResearchCard[] = [
  {
    ticker: "AAVE",
    name: "Aave",
    slug: "aave-aave",
    date: "2025-01-11",
    sectors: ["defi"],
    category: "Altcoins Outlook · DeFi",
    valuationAtReport: "$4B",
    supply: "Circ 15M · Total/Max 16M",
    thesis:
      "Protokol lending DeFi pionir & blue-chip — pasar uang non-kustodian yang matang dengan arus kas nyata dan komunitas besar.",
    what:
      "Money market terdesentralisasi (sejak 2020, Ethereum + multi-chain: Polygon, Avalanche). Deposit aset ke liquidity pool untuk bunga; pinjam secara overcollateralized. Token $AAVE = governance + staking (jaminan keamanan protokol). Fitur khas: flash loan (pinjam tanpa jaminan asal lunas dalam 1 transaksi).",
    bull: [
      "Blue-chip DeFi paling matang & teruji, arus kas & TVL besar",
      "Sharpe ratio 90-hari ~2,45 (return bagus relatif risiko)",
      "Komunitas kuat (>614K followers Jan 2025) → likuiditas & adopsi",
      "Multi-chain, fitur flash loan jadi pembeda",
    ],
    risks: [
      "Risiko eksploitasi smart contract",
      "Volatilitas aset jaminan → risiko likuidasi",
      "Persaingan ketat (Compound, MakerDAO)",
    ],
    verdict:
      "Salah satu DeFi blue-chip paling solid. Saat report harga retest weekly demand $200–$300 (area scale-in).",
    narratives: ["DeFi", "Lending", "Blue-chip"],
  },
  {
    ticker: "MKR",
    name: "Maker",
    slug: "maker-mkr",
    date: "2024-12-25",
    sectors: ["defi", "rwa"],
    category: "Altcoins Outlook · DeFi",
    valuationAtReport: "$1.4B",
    supply: "Circ 891K · Total 919K · Max 1M",
    thesis:
      "Penerbit stablecoin terdesentralisasi $DAI — pelopor CDP/collateralized debt yang jadi fondasi DeFi, dengan token tata kelola deflatif.",
    what:
      "MakerDAO (tata kelola) + Maker Protocol (mesin) yang mencetak stablecoin $DAI (patok $1) lewat sistem Vault: kunci ETH/WBTC/USDC sebagai jaminan (biasanya 60–75% LTV), bayar stability fee. $MKR = governance + memiliki mekanisme deflasi (dibakar dari surplus).",
    bull: [
      "Pelopor & fondasi DeFi, $DAI stablecoin desentralisasi paling teruji",
      "$MKR deflatif (buyback-burn dari pendapatan protokol)",
      "Model transparan, tahan sensor vs stablecoin tersentralisasi (USDT/USDC)",
    ],
    risks: [
      "Kompleksitas & ketergantungan pada nilai jaminan",
      "Risiko smart contract & likuidasi saat jaminan turun tajam",
      "Persaingan stablecoin & DeFi",
    ],
    verdict:
      "Blue-chip DeFi yang mencetak model keuangan baru; nilai jangka panjang di utilitas $DAI + deflasi $MKR.",
    narratives: ["DeFi", "Stablecoin", "RWA"],
  },
  {
    ticker: "HYPE",
    name: "Hyperliquid",
    slug: "hyperliquid-hype",
    date: "2024-12-23",
    sectors: ["layer1", "defi"],
    category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$8B",
    supply: "Circ 333M · Total/Max 1B",
    extra: [{ label: "Harga saat report", value: "$27" }],
    thesis:
      "Perp DEX 'fully onchain' — versi Binance yang sepenuhnya di blockchain; order book cepat, fee rendah, flywheel likuiditas.",
    what:
      "Platform trading (perpetual/futures leverage) yang semua aktivitasnya on-chain, bukan CEX. Flywheel: order book efisien → menarik app pihak ketiga → volume & order flow naik → likuiditas market maker masuk → order book makin kuat.",
    bull: [
      "Inovatif: pengalaman CEX tapi fully onchain (transparan, self-custody)",
      "Low price impact → menarik institusi & trader volume besar",
      "Tokenomics pro-komunitas: 38,89% future emissions/rewards + 31% airdrop Genesis",
      "Momentum & thesis 'inovasi paling cemerlang' saat itu",
    ],
    risks: [
      "Alokasi tim inti besar (Core 23,8% + Foundation 15%) → kekhawatiran desentralisasi & tekanan jual",
      "Community grants sangat kecil (0,30%)",
      "Keberlanjutan bergantung pada 'hype' & eksekusi jangka panjang",
    ],
    verdict:
      "Salah satu inovasi DEX paling menarik siklus ini ('fully onchain Binance'); pantau eksekusi & unlock kontributor.",
    narratives: ["Layer-1", "DEX", "Perp"],
  },
  {
    ticker: "SOL",
    name: "Solana",
    slug: "solana-sol",
    date: "2024-11-05",
    sectors: ["layer1"],
    category: "Altcoins Outlook · Investing Idea",
    valuationAtReport: "$75B",
    supply: "Circ 470M · Total 587M · Max ∞",
    thesis:
      "Layer-1 super cepat yang jadi 'pembunuh Ethereum' di siklus 2024–25 — ekosistem meledak, keuangan menguat, tapi relatif tersentral & VC-heavy.",
    what:
      "Blockchain untuk dApps dengan fokus kecepatan & biaya rendah. Konsensus unik Proof of History (PoH) + PoS + parallel processing → TPS tinggi (ideal DeFi/NFT/gaming/DePIN). Diluncurkan 2020 oleh Anatoly Yakovenko.",
    bull: [
      "Ekosistem tumbuh sangat cepat, hampir mengejar Ethereum (DeFi, DePIN, Consumer, Payments)",
      "Metrik keuangan Q3 2024 naik signifikan (revenue, TVL, volume)",
      "Kenaikan harga selaras kenaikan TVL → dinilai 'fair value'",
      "Distribusi lumayan merata (38% komunitas, 12,8% dev, 5,2% validator)",
    ],
    risks: [
      "Relatif tersentral: Nakamoto coefficient <20, hanya ~1.373 validator aktif",
      "Alokasi early investor tinggi (~31%) → potensi selling pressure",
      "Heavily VC-backed (a16z, Multicoin, Polychain, Coinbase Ventures, Alameda)",
      "Teknologi altcoin mudah tergantikan — 'pembunuh Solana' berikutnya bisa muncul",
    ],
    verdict:
      "Salah satu 'The Winners' siklus 2024–25, cemerlang di dalam & luar — tapi tetap altcoin berisiko tinggi.",
    narratives: ["Layer-1", "Ethereum-killer", "The Winners"],
  },
  {
    ticker: "TAO",
    name: "Bittensor",
    slug: "bittensor-tao",
    date: "2024-08-20",
    sectors: ["ai", "depin"],
    category: "Investing Idea",
    rating: "HOLD",
    valuationAtReport: "$2.3B",
    supply: "Circ 7.2M · Max 21M",
    thesis:
      "'Bitcoin-nya AI' — jaringan AI terdesentralisasi yang memberi insentif kontribusi model AI dengan token $TAO, meniru model reward penambang Bitcoin.",
    what:
      "Blockchain untuk mengembangkan, melatih, & memakai model AI secara terbuka/terdesentralisasi. Kontribusi AI dinilai objektif & diberi imbalan $TAO — menghilangkan ketergantungan pada entitas terpusat. Max supply 21M meniru Bitcoin.",
    bull: [
      "Menyatukan DUA narasi besar sekaligus: AI + DePIN",
      "Model insentif à la Bitcoin untuk AI (unik & powerful)",
      "AI & DePIN digadang jadi sektor besar di bull run 2024–25",
    ],
    risks: [
      "Altcoin AI berisiko tinggi, teknologi cepat berubah",
      "Tidak ada garansi; perlu manajemen risiko",
      "Invalidasi teknikal di bawah $237 (saat report)",
    ],
    verdict:
      "HOLD. 'Melempar dua burung dengan satu batu' (AI+DePIN); potensi teknikal ke $600, invalidasi <$237.",
    narratives: ["AI", "DePIN"],
  },
  {
    ticker: "ETH",
    name: "Ethereum",
    slug: "ethereum-eth",
    date: "2024-04-30",
    sectors: ["layer1", "macro"],
    category: "Market Outlook",
    thesis:
      "Induk semua altcoin yang 'underperformed' vs Bitcoin & Solana di 2023 — tapi secara proyek terus membaik; undervalue dengan katalis Dencun + potensi ETF.",
    what:
      "Layer-1 smart contract pertama, fondasi mayoritas altcoin & dApps. 'Ratu' crypto (Bitcoin 'raja'). Pendapatan kumulatif setara raksasa teknologi (Microsoft, Adobe, dst).",
    bull: [
      "Masih 'underperformed' vs BTC (2023: BTC +163% vs ETH +97%) → ruang catch-up",
      "Dencun Update (Mar 2024) tingkatkan efisiensi & turunkan gas fee Layer-2",
      "Katalis potensi persetujuan ETF-ETH oleh SEC",
      "Nilai intrinsik proyek kuat & terus improvement",
    ],
    risks: [
      "Kalah pamor & utilitas dari Solana (2023 SOL +700%)",
      "Kompetisi Layer-1 makin sengit",
      "Ketergantungan pada realisasi katalis (ETF, adopsi L2)",
    ],
    verdict:
      "Undervalue vs BTC dengan katalis positif; teknikal berpotensi retest area ~$2.900 (trendline bullish weekly).",
    narratives: ["Layer-1", "ETF", "Undervalue"],
  },
  {
    ticker: "ONDO",
    name: "Ondo Finance",
    slug: "ondo-finance-ondo",
    date: "2024-02-19",
    sectors: ["rwa", "defi"],
    category: "Investing Idea",
    rating: "HOLD",
    valuationAtReport: "$400M",
    supply: "Circ 1.4B · Max 10B",
    extra: [
      { label: "Upside potential", value: "±1000%" },
      { label: "Avg 6m daily T/O", value: "US$25.2M" },
    ],
    thesis:
      "Pemain utama narasi RWA/tokenisasi — 'bisa membuka pasar triliunan dolar' saat aset dunia nyata dibawa on-chain.",
    what:
      "Proyek tokenisasi Real World Asset (RWA): mengubah aset nyata (obligasi, sekuritas, produk) jadi token yang bisa diperdagangkan — meningkatkan likuiditas & transparansi, mengurangi monopoli/sengketa kepemilikan.",
    bull: [
      "Narasi RWA = sektor paling diincar VC & institusi (BlackRock/Larry Fink pro-tokenisasi)",
      "Pasar tokenisasi diproyeksi tumbuh dari ~$116B → $3.49T–$9.95T (2030)",
      "Tiga jenis tokenisasi (uang, sekuritas, produk) semua bertumbuh",
    ],
    risks: [
      "Max supply besar (10B) vs circulating 1.4B → potensi dilusi/unlock",
      "Narasi masih awal; realisasi valuasi triliunan butuh waktu & regulasi",
      "Altcoin berisiko tinggi",
    ],
    verdict:
      "HOLD. Salah satu proxy terkuat narasi RWA dengan upside besar (±1000%) jika tokenisasi terealisasi.",
    narratives: ["RWA", "Tokenisasi", "Institutional"],
  },

  // ── Batch: 2024–2025 reports (distilled) ──
  {
    ticker: "AKT", name: "Akash Network", slug: "akash-network-akt", date: "2024-08-20",
    sectors: ["depin", "ai"], category: "Investing Idea · DePIN", rating: "HOLD",
    valuationAtReport: "$650M", supply: "Circ 247M · Max 248M",
    thesis: "Marketplace komputasi awan terdesentralisasi yang menawarkan harga jauh lebih murah dari AWS/GCP lewat model pasar terbuka; kandidat kuat di narasi DePIN dan AI/rendering.",
    what: "Akash adalah platform cloud computing terdesentralisasi di mana pemilik server menjual kapasitas komputasi ke pasar terbuka. Harga ditentukan supply-demand sehingga lebih murah dan fleksibel dibanding cloud terpusat. Open-source, cocok untuk beban kerja GPU dan AI.",
    bull: ["Biaya komputasi jauh di bawah cloud tradisional", "Aktivitas Q2 2024 naik 44% QoQ (rekor tertinggi)", "Kapasitas GPU melonjak 91%, provider +8%", "Potensi jadi platform rendering pilihan di era AI"],
    risks: ["Persaingan DePIN ketat (Render, Filecoin)", "Aset volatil, bergantung siklus pasar", "Butuh adopsi enterprise berkelanjutan"],
    verdict: "AC menilai Akash di area teknikal ideal untuk akumulasi (target awal $3.5, potensi $6); eksposur DePIN yang layak, invalidasi di bawah $1.95.",
    narratives: ["DePIN", "AI", "Cloud Computing"],
  },
  {
    ticker: "ARB", name: "Arbitrum", slug: "arbitrum-arb", date: "2024-10-23",
    sectors: ["layer2", "defi"], category: "Altcoins Outlook · Layer-2",
    valuationAtReport: "$2.2B", supply: "Circ 3.9B · Total/Max 10B",
    thesis: "Salah satu 'pemenang' Layer-2 Ethereum yang saat report underperformed bersama ETH, tapi punya fundamental, TVL, dan dukungan smart money terkuat di sektornya.",
    what: "Arbitrum adalah solusi Layer-2 di atas Ethereum yang memakai Optimistic Rollup untuk memproses transaksi off-chain lalu menyelesaikan hasilnya di L1. Kompatibel penuh EVM lewat ArbOS sehingga dApps Ethereum mudah bermigrasi.",
    bull: ["TPS hingga 40.000, jauh di atas Optimism (2.000)", "Gas sangat murah (~$0.11/tx)", "TVL tinggi (Arbitrum One >$1.9B)", "DAO treasury besar 42.78% + backing VC top (Lightspeed, Polychain, Pantera)"],
    risks: ["Alokasi tim+investor besar (44.47%) → tekanan jual", "Airdrop 11.62% menambah selling pressure", "Sangat bergantung pemulihan performa Ethereum"],
    verdict: "Teknikal bottoming di weekly chart (breakout & retest), peluang scale-in salah satu 'winner' L2; batasi hold jangka panjang maks 3% modal.",
    narratives: ["Layer-2", "Ethereum", "Rollup"],
  },
  {
    ticker: "ARKM", name: "Arkham", slug: "arkham-arkm", date: "2025-01-02",
    sectors: ["ai", "data"], category: "Altcoins Outlook · Crypto Platform",
    valuationAtReport: "$500M", supply: "Circ 333M · Total/Max 1B",
    thesis: "Platform intelijen on-chain berbasis AI yang memetakan aktivitas wallet dan entitas; menarik di persimpangan narasi AI dan analitik data blockchain.",
    what: "Arkham Intelligence adalah platform analitik blockchain yang mengidentifikasi entitas di balik alamat wallet dan memvisualisasikan aliran dana real-time. Memakai AI untuk menganalisis pola transaksi. Punya Bounty Program untuk mengungkap data sulit dijangkau.",
    bull: ["Fitur pemetaan wallet & intelijen on-chain unik", "AI-driven, selaras booming narasi AI", "Bounty Program memperluas cakupan data komunitas", "Unlock terukur (~33% awal 2025)"],
    risks: ["Sebagian besar supply belum unlock (potensi dilusi)", "Persaingan tool analitik lain (Nansen dll)", "Adopsi masih perlu dibuktikan lintas siklus"],
    verdict: "AC menilai all-time chart Arkham masih berpotensi breakout jangka panjang dan menarik di era booming AI; tokenomics sehat dengan unlock terukur.",
    narratives: ["AI", "On-chain Data", "Analytics"],
  },
  {
    ticker: "ATH", name: "Aethir", slug: "aethir-ath", date: "2024-12-21",
    sectors: ["depin", "ai", "gaming"], category: "Altcoins Outlook · DePIN",
    valuationAtReport: "$427M", supply: "Circ 5.6B · Total/Max 42B (full unlock 2029)",
    thesis: "Platform cloud computing terdesentralisasi berbasis edge yang menyasar Web3, gaming, dan AI; pesaing DePIN dengan dukungan smart money kuat.",
    what: "Aethir adalah platform decentralized cloud computing dengan arsitektur edge computing (node tersebar global) untuk menekan latensi dan biaya. Dirancang kompatibel dengan Web3/dApps/smart contract; menyewa kapasitas GPU lewat jaringan P2P.",
    bull: ["Edge computing menurunkan latensi & biaya", "Backing smart money kuat (Framework, HashKey, Merit Circle, Animoca)", "Fokus gaming/metaverse/AI yang tumbuh", "Valuasi ~$400M masih bersaing dengan Render & Akash"],
    risks: ["Total supply sangat besar (42B), unlock hingga 2029", "Selling pressure dari vesting bertahap", "Kompetisi DePIN GPU ketat", "Token relatif baru (listing Jul 2024)"],
    verdict: "AC melihat setup new-listing yang siap breakout dengan momentum pembeli menguat; peluang bersaing di DePIN, cermati jadwal unlock panjang.",
    narratives: ["DePIN", "AI", "Gaming"],
  },
  {
    ticker: "AVAX", name: "Avalanche", slug: "avalanche-avax", date: "2024-11-06",
    sectors: ["layer1", "defi"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$10B", supply: "Circ 407M · Total 447M · Max 720M",
    thesis: "Layer-1 solid dengan ekosistem DeFi/NFT/gaming berkembang, tapi menunjukkan tanda sedikit overvaluation dan revenue menurun tajam dibanding 2024.",
    what: "Avalanche adalah blockchain open-source Layer-1 dari Ava Labs (2020) untuk dApps dan subnet kustom. Konsensus snowball sampling memberi finalitas <2 detik, biaya rendah, hemat energi. AVAX untuk gas, staking, insentif validator.",
    bull: ["Finalitas sangat cepat (<2 detik), biaya rendah", "Ekosistem DeFi tumbuh (Aave market share 44%, +25% QoQ)", "Supply stablecoin naik 13% QoQ ke $1.7B", "50% alokasi untuk staking rewards"],
    risks: ["Indikasi overvaluation (harga jauh di atas TVL)", "Revenue drop signifikan vs 2024", "Distribusi token kompleks & kurang transparan"],
    verdict: "Proyek solid dengan ekosistem menarik, namun butuh terobosan besar untuk bersaing dengan L1 papan atas dan mengoreksi valuasi yang agak mahal.",
    narratives: ["Layer-1", "DeFi", "Smart Contract"],
  },
  {
    ticker: "BNB", name: "BNB", slug: "bnb-bnb", date: "2024-11-07",
    sectors: ["layer1", "defi"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$87B", supply: "Circ 145M · Total 145M · Max 200M",
    thesis: "Layer-1 'pemenang' yang tahan banting sebagai blue chip Top 10, dikatrol CEX Binance meski hype BSC tak sekuat 2021.",
    what: "BNB adalah koin native BNB Smart Chain (BSC), Layer-1 untuk dApps dan smart contract dengan transaksi cepat dan murah. Konsensus Proof of Staked Authority (PoSA). Arsitektur: Beacon Chain, BSC, zkRollup L2, sidechain khusus.",
    bull: ["Blue chip Top 10, dianggap 'safe haven' altcoin", "Dikatrol Binance, CEX terbesar dunia", "DeFi di BSC naik 46% QoQ di Q2 2024", "Tidak ada lagi potensi inflasi setelah token terbit penuh"],
    risks: ["TVL & revenue turun drastis vs 2021", "Kalah cepat/murah dari Solana", "Sangat bergantung nasib & regulasi Binance"],
    verdict: "Blue chip yang akan terus terkatrol selama CEX-nya bersinar dan sudah terbukti tahan pressure test; alternatif safe haven di antara altcoin.",
    narratives: ["Layer-1", "CEX", "Blue Chip"],
  },
  {
    ticker: "CARV", name: "CARV", slug: "carv-carv", date: "2024-12-22",
    sectors: ["data", "ai", "infra"], category: "Altcoins Outlook · Web3 Infrastructure",
    valuationAtReport: "$161M", supply: "Circ 163M · Total/Max 1B",
    thesis: "Infrastruktur Web3 untuk agregasi data on-chain, identitas digital, dan AI/gaming; token baru fase konsolidasi dengan distribusi condong ke komunitas.",
    what: "CARV adalah platform agregasi & analisis data on-chain yang membangun identitas/reputasi digital interoperable lintas chain. Memakai TEE dan CARVLink untuk enkripsi/verifikasi lalu simpan di IPFS/Arweave. Ada gamification untuk partisipasi.",
    bull: ["Aktivitas pengguna naik 5x YoY di 8 chain", "Momentum kampanye Data to Earn & verifier node sale", "50% supply ke komunitas", "Di persimpangan narasi AI, data, dan gaming"],
    risks: ["Isu privasi & keamanan data sensitif", "Tantangan adopsi & integrasi lintas ekosistem", "Total supply besar (1B), sebagian belum unlock", "Masih konsolidasi new-listing"],
    verdict: "AC menilai CARV proyek menarik yang patut dipertimbangkan; berpotensi breakout bila volume naik menandakan akumulasi.",
    narratives: ["Web3 Data", "AI", "Gaming"],
  },
  {
    ticker: "EIGEN", name: "EigenLayer", slug: "eigenlayer-eigen", date: "2024-10-23",
    sectors: ["infra", "defi"], category: "Altcoins Outlook · Investing Idea",
    valuationAtReport: "$651M", supply: "Circ 186M · Total 1.6B · Max ∞",
    thesis: "Pelopor restaking Ethereum yang memungkinkan ETH staked mengamankan protokol baru; utilitas tinggi dengan dukungan smart money kuat, meski max supply tak terbatas.",
    what: "EigenLayer adalah protokol di atas Ethereum yang mempopulerkan restaking: ETH yang sudah di-stake dipakai kembali untuk mengamankan protokol lain (AVS) tanpa modal tambahan. 'Modular security' via marketplace antara user, LRT, operator, dan AVS.",
    bull: ["Pelopor & pemimpin narasi restaking", "TVL tumbuh pesat hingga $20B (Jun 2024)", "Stakedrop mendorong partisipasi kuat", "Backing smart money top (Polychain, Coinbase, a16z-tier)"],
    risks: ["Max supply tak terbatas (potensi inflasi)", "Konsentrasi investor+kontributor tinggi (29.5% & 25.5%)", "Risiko sistemik restaking (cascading slashing)"],
    verdict: "Menarik dibeli dari daily chart (breakout & retest) dengan utilitas tinggi di siklus 2024-25; batasi hold jangka panjang maks 3% modal.",
    narratives: ["Restaking", "Ethereum", "Infrastructure"],
  },
  {
    ticker: "ENA", name: "Ethena", slug: "ethena-ena", date: "2024-05-03",
    sectors: ["defi", "payments"], category: "Investing Idea · Quick Flip",
    thesis: "Stablecoin sintetis yield tinggi yang di-back aset digital nyata (bukan seperti Terra), tapi tokenomics lemah membuatnya lebih cocok untuk quick flip ketimbang hold jangka panjang.",
    what: "Ethena adalah protokol stablecoin (USDe) yang dipatok 1:1 ke USD dan menawarkan yield hingga 27%. Beda dari Terra, di-back aset digital stabil dan menjaga peg lewat delta hedging via posisi futures. Yield dari staking ETH.",
    bull: ["Di-back aset digital nyata (bukan token sendiri seperti LUNA)", "Delta hedging jaga peg lebih tahan", "Yield tinggi hingga 27%", "Backing smart money (Binance Labs, OKX, Arthur Hayes)"],
    risks: ["Tokenomics lemah, tim pegang token sangat banyak", "Max supply tak terbatas → tidak ideal hold jangka panjang", "Sering dijuluki 'the next Terra/LUNA'", "Yield rentan saat funding rate negatif"],
    verdict: "AC memandang ENA sebagai peluang quick flip jangka pendek yang lebih menguntungkan dibanding hold; cermati area $1 dan $1.4.",
    narratives: ["Stablecoin", "DeFi", "Yield"],
  },
  {
    ticker: "FTM", name: "Fantom", slug: "fantom-ftm", date: "2024-12-27",
    sectors: ["layer1", "defi"], category: "Altcoins Outlook · Blockchain Infrastructure",
    valuationAtReport: "$2.4B", supply: "Circ 2.8B · Total/Max 3B",
    thesis: "Layer-1 berbasis DAG dengan finalitas sub-detik dan ekosistem DeFi berkembang; struktur pasar bullish dan sempat outperform BTC/ETH/SOL di Q3 2024.",
    what: "Fantom adalah platform smart contract Layer-1 dengan Directed Acyclic Graph (DAG) dan konsensus Lachesis (aBFT PoS) untuk finalitas hampir instan (<1 detik). Kompatibel EVM. FTM untuk gas, staking, governance.",
    bull: ["Finalitas transaksi <1 detik lewat Lachesis/DAG", "Market cap FTM naik 18% Q3 2024, ungguli BTC/ETH/SOL", "Stablecoin cap stabil $321M (USDC dominan)", "Kompatibel EVM, migrasi dApps mudah"],
    risks: ["Persaingan Layer-1 sangat ketat", "Bergantung eksekusi (transisi ke Sonic)", "Perlu likuiditas & adopsi DeFi berkelanjutan"],
    verdict: "AC menilai Fantom kompetitif di sektor Layer-1, dengan price action weekly yang masih membentuk struktur bullish.",
    narratives: ["Layer-1", "DeFi", "DAG"],
  },
  {
    ticker: "GALA", name: "Gala", slug: "gala-gala", date: "2024-12-25",
    sectors: ["gaming", "infra"], category: "Altcoins Outlook · Gaming Infrastructure",
    valuationAtReport: "$1.6B", supply: "Circ 42B · Total 42B · Max 50B",
    thesis: "Infrastruktur gaming blockchain matang yang mengembalikan kepemilikan aset ke pemain; menunjukkan tanda akumulasi smart money dan Sharpe ratio membaik.",
    what: "Gala adalah platform blockchain untuk game terdesentralisasi yang memberi pemain kepemilikan penuh atas aset in-game. Didirikan 2019 oleh Eric Schiermeyer (co-founder Zynga). Didukung Gala Nodes yang memberi reward $GALA/NFT dan hak governance.",
    bull: ["Proyek matang & mapan sejak 2020", "Volume naik signifikan awal Des 2024 → akumulasi", "Sharpe ratio membaik ke 1.55", "Founder berpengalaman (eks-Zynga/FarmVille)"],
    risks: ["Supply sangat besar (42B beredar, max 50B)", "Sektor GameFi kompetitif & bergantung hype", "Butuh judul game sukses untuk adopsi"],
    verdict: "Proyek gaming matang dengan potensi continuation jangka panjang dan area pembelian solid di weekly demand didukung akumulasi volume.",
    narratives: ["Gaming", "NFT", "Infrastructure"],
  },
  {
    ticker: "GRASS", name: "Grass", slug: "grass-grass", date: "2024-12-23",
    sectors: ["depin", "ai"], category: "Altcoins Outlook · Artificial Intelligence",
    valuationAtReport: "$581M", supply: "Circ 243M · Max 1B",
    thesis: "Memonetisasi bandwidth internet menganggur pengguna untuk memasok kebutuhan jaringan AI — pendekatan DePIN-AI inovatif menjelang rally proyek AI Q1 2025.",
    what: "Grass menjalankan aplikasi desktop di latar belakang yang menyewakan bandwidth tak terpakai untuk mendukung ekonomi AI, dengan imbalan token GRASS. Fokus keamanan/privasi (hanya bandwidth dibagi, bukan data pribadi). Sudah 2,5 juta+ pengguna aktif.",
    bull: ["2,5 juta+ pengguna aktif global", "Selaras narasi AI (prediksi rally Q1 2025)", "Alokasi pro-komunitas (30%) + ekosistem (22,8%)", "Model monetisasi bandwidth yang unik"],
    risks: ["Alokasi investor besar (25,2%) berisiko manipulasi whale", "Airdrop rawan selling pressure jangka pendek", "Kurang transparansi jadwal vesting", "Volatilitas tinggi proyek baru"],
    verdict: "Proyek AI-DePIN menarik untuk dipertimbangkan dengan pengendalian risiko dan sizing yang tepat, terutama jika narasi AI menguat Q1 2025.",
    narratives: ["AI", "DePIN", "Bandwidth"],
  },
  {
    ticker: "HNT", name: "Helium", slug: "helium-hnt", date: "2024-10-29",
    sectors: ["depin"], category: "Altcoins Outlook · DePIN",
    valuationAtReport: "$1.1B", supply: "Circ 171M · Max 223M",
    thesis: "Salah satu proyek DePIN paling matang yang membangun jaringan telekomunikasi fisik terdesentralisasi, dengan pertumbuhan bisnis nyata yang melonjak sejak migrasi ke Solana.",
    what: "Helium menghubungkan perangkat fisik (sensor, IoT, mobile) lewat hotspot komunitas, memakai GPS untuk verifikasi lokasi dan blockchain sebagai buku besar transparan. Operator hotspot dapat reward atas jangkauan. Migrasi ke Solana mendongkrak adopsi.",
    bull: ["Hotspot naik 3x (2rb → 7rb+) dalam 2024", "Migrasi Solana menambah 367.000 pengguna", "Konsumsi network naik ~700% ke $720K", "Unlock bertahap hingga 7 tahun, selling pressure terkendali"],
    risks: ["Alokasi 21,5% untuk investor awal (7 tahap ICO)", "Ketergantungan pada performa jaringan Solana", "Tidak ada jaminan retest ATH ($35 di 2022)"],
    verdict: "Berpeluang continuation di weekly chart pada dynamic EMA; cocok hold jangka panjang dengan alokasi maks 3% modal.",
    narratives: ["DePIN", "IoT", "Solana"],
  },
  {
    ticker: "ICP", name: "Internet Computer", slug: "internet-computer-icp", date: "2024-12-04",
    sectors: ["layer1", "infra"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$6.9B", supply: "Circ 475M · Max ∞",
    thesis: "Layer-1 yang memungkinkan dApp berjalan penuh di blockchain tanpa server tradisional, kandidat kuat dari revival koin siklus 2021.",
    what: "Dikembangkan DFINITY (Zurich), ICP menjalankan backend/data/logika aplikasi sepenuhnya on-chain lewat smart contract 'canisters'. Klaim finalitas 1-2 detik dan kapasitas data besar. Tata kelola via Network Nervous System (NNS) dengan neuron staking.",
    bull: ["Teknologi canister efisien untuk skala besar", "Finalitas cepat 1-2 detik", "Ekosistem lengkap (DeFi, NFT, DAO, games)", "Kandidat revival koin siklus 2021"],
    risks: ["Dinilai terlalu tersentral, DFINITY pegang 22% sirkulasi", "Alokasi komunitas/airdrop sangat kecil (1,1%)", "TVL di bawah $100M", "Max supply tak terbatas (inflasi)"],
    verdict: "Layer-1 mapan yang layak diperhatikan seiring tren kenaikan koin siklus 2021, meski isu sentralisasi dan ekosistem yang belum melahirkan proyek besar patut dicermati.",
    narratives: ["Layer-1", "dApps", "Serverless"],
  },
  {
    ticker: "JUP", name: "Jupiter", slug: "jupiter-jup", date: "2024-12-05",
    sectors: ["defi"], category: "Altcoins Outlook · Decentralized Exchange (DEX)",
    valuationAtReport: "$1.7B", supply: "Circ 1.35B · Max 10B",
    thesis: "Agregator DEX terdepan di Solana yang mengumpulkan likuiditas lintas AMM, dinilai undervalued relatif terhadap TVL-nya yang melejit.",
    what: "Dibangun di Solana, Jupiter mengagregasi likuiditas dari berbagai DEX/AMM (Raydium, Orca, dll) dan memakai algoritma berbasis graf untuk cari jalur trading terbaik (volume, gas, slippage). Token governance $JUP diluncurkan Jan 2024.",
    bull: ["Kontribusi $749 juta ke TVL DeFi Solana Q3 2024", "10,4% pangsa liquid staking Solana", "TVL parabolik, harga masih konsolidasi (undervalued)", "Beneficiary langsung momentum Solana"],
    risks: ["Sangat bergantung stabilitas jaringan Solana", "Persaingan ketat antar agregator DEX", "Volatilitas token", "Sirkulasi baru ~13,5% dari max supply"],
    verdict: "Jika bullish terhadap Solana, Jupiter menarik sebagai infrastruktur transaksinya; metrik menunjukkan proyeksi naik dengan valuasi masih undervalued vs TVL.",
    narratives: ["DeFi", "DEX", "Solana"],
  },
  {
    ticker: "KAS", name: "Kaspa", slug: "kaspa-kas", date: "2024-12-23",
    sectors: ["layer1"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$3B", supply: "Circ 25B · Max 28.7B",
    thesis: "Layer-1 PoW berbasis blockDAG yang memproses blok paralel dengan block time ~1 detik, menawarkan skalabilitas tanpa mengorbankan desentralisasi.",
    what: "Kaspa memakai arsitektur blockDAG (DAG), berbeda dari blockchain linear, sehingga banyak blok diproses paralel dengan throughput tinggi. Konsensus PoW; mendukung solo-mining bahkan hashrate rendah. Fair launch tanpa pre-mine/pre-sale/alokasi tim.",
    bull: ["Block time ~1 detik, cocok aplikasi real-time", "Fair launch tanpa pre-mine/alokasi tim", "Tahan 51% attack, desentralisasi kuat", "Didukung Mara Digital Holdings (miner BTC besar)"],
    risks: ["Konsolidasi harga $0,1-$0,2 menunggu momentum", "PoW menghadapi kompetisi Layer-1 lain", "Supply beredar sudah sangat besar (25B)"],
    verdict: "Paradigma blockDAG inovatif dengan dukungan Mara menjadikan Kaspa menarik dicermati saat market kembali run-up menjelang bull run 2025.",
    narratives: ["Layer-1", "blockDAG", "PoW"],
  },
  {
    ticker: "LTC", name: "Litecoin", slug: "litecoin-ltc", date: "2024-12-30",
    sectors: ["payments"], category: "Altcoins Outlook · Payments",
    valuationAtReport: "$7.5B", supply: "Circ 75M · Max 84M",
    thesis: "Salah satu altcoin tertua yang tetap relevan sebagai 'perak' Bitcoin, dengan likuiditas tinggi dan fungsi pembayaran yang efisien.",
    what: "Diluncurkan 2011 oleh Charlie Lee sebagai alternatif Bitcoin yang lebih cepat/ringan. PoW berbasis Scrypt dengan block time 2,5 menit (4x lebih cepat dari BTC) dan biaya rendah. Sering jadi testbed teknologi (SegWit, Lightning). Max 84 juta koin.",
    bull: ["Likuiditas tinggi, hadir di hampir semua exchange utama", "Volume transaksi puncak 8 miliar+ Des 2024", "Track record 1 dekade+ dan komunitas solid", "Testbed teknologi terpercaya (SegWit, Lightning)"],
    risks: ["Volatilitas tinggi", "Narasi/utilitas relatif stagnan dibanding chain baru", "Sedang koreksi di weekly chart"],
    verdict: "Chart yearly menunjukkan koreksi di weekly yang bisa jadi area 'scale in' bila tren market berlanjut; aset mapan untuk jangka panjang maupun spekulasi.",
    narratives: ["Payments", "OG", "Store of Value"],
  },
  {
    ticker: "MANTA", name: "Manta Network", slug: "manta-network-manta", date: "2024-03-07",
    sectors: ["layer2", "privacy"], category: "Investing Idea · Layer-2", rating: "HOLD",
    valuationAtReport: "$875M", supply: "Circ 251M · Max 1.2B",
    extra: [{ label: "Upside", value: "±400%" }, { label: "Fair Value", value: "$3B-$4B" }],
    thesis: "Proyek Layer-2 unik dengan sistem dual-network (Manta Pacific + Manta Atlantic), diuntungkan sentimen Dencun Update dan masih undervalued di bawah $1B.",
    what: "Manta punya dua jaringan: Manta Pacific (L2 di atas Ethereum) dan Manta Atlantic (L1 di atas Polkadot), memberikan fitur 2-in-1 dengan zero-knowledge proofs. Momentum didorong Dencun Update (proto-danksharding EIP-4844) yang menurunkan biaya L2.",
    bull: ["Arsitektur dual-network (L1 Polkadot + L2 Ethereum) yang unik", "Diuntungkan Dencun & narasi Ethereum ETF", "Valuasi masih <$1B, fair value dinilai $3B-$4B", "TVL sektor Layer-2 naik 2x ($17B → $36B)"],
    risks: ["Persaingan ketat Layer-2 (MATIC, OP, ARB, METIS)", "Proyek baru dengan volatilitas tinggi", "Sirkulasi baru ~21% dari max supply"],
    verdict: "Rating HOLD dengan potensi upside ±400%; dinilai undervalue signifikan dengan target teknikal $5,5-$8, namun tetap perlu riset mandiri.",
    narratives: ["Layer-2", "ZKP", "Dencun"],
  },
  {
    ticker: "METIS", name: "Metis", slug: "metis-metis", date: "2025-01-06",
    sectors: ["layer2"], category: "Altcoins Outlook · Layer-2",
    valuationAtReport: "$298M", supply: "Circ 6M · Max 10M",
    thesis: "Layer-2 Ethereum berbasis Optimistic Rollups yang fokus pada infrastruktur ekonomi terdesentralisasi (DACs), berpeluang bottoming saat momentum market pick-up.",
    what: "Metis memindahkan beban transaksi ke Layer-2 dengan Optimistic Rollups, memangkas gas hingga 90% vs mainnet. Fitur: Ranger System (percepat validasi) dan Middleware Layer. Diferensiasi: fokus Decentralized Autonomous Companies (DACs).",
    bull: ["Gas hingga 90% lebih murah dari mainnet Ethereum", "Fokus unik pada DACs + smart contract modular", "Alokasi 47,7% Transaction Mining untuk insentif", "Pertumbuhan konsisten alamat baru & aktif"],
    risks: ["Persaingan ketat (Optimism, Arbitrum, zkRollups)", "Delay finalisasi Optimistic Rollups", "Alokasi airdrop kecil (6%)", "Market cap kecil, likuiditas terbatas"],
    verdict: "Layer-2 menarik dengan tokenomics strategis dan adopsi stabil; peluang bottoming di weekly chart menjadikannya kandidat saat momentum market menguat.",
    narratives: ["Layer-2", "Optimistic Rollup", "DAC"],
  },
  {
    ticker: "MORPHO", name: "Morpho", slug: "morpho-morpho", date: "2024-12-04",
    sectors: ["defi"], category: "Altcoins Outlook · DeFi",
    valuationAtReport: "$200M", supply: "Circ 134M · Max 1B",
    thesis: "Protokol lending DeFi yang mengoptimalkan efisiensi suku bunga lewat lapisan peer-to-peer di atas Aave/Compound, dengan performa on-chain yang melonjak.",
    what: "Morpho adalah layer di atas protokol lending, menawarkan return lebih tinggi untuk lender dan bunga lebih rendah untuk borrower. Menggabungkan matching P2P dengan fallback pool (Aave/Compound) agar aset tetap produktif. Sepenuhnya on-chain.",
    bull: ["TVL 'goes parabolic', harga masih konsolidasi", "Net Deposit +50%, TVL +47%, pinjaman +53% ke $1,35B (30 hari)", "Pengguna aktif bulanan +33% ke 28K", "Backing smart money (a16z, Coinbase Ventures, Pantera)"],
    risks: ["~90% token masih akan beredar (proyek baru)", "Alokasi strategic partner besar (27,5%) + founder 15%", "Risiko smart contract layer di atas protokol lain"],
    verdict: "Inovator DeFi lending dengan performa on-chain kuat dan dukungan smart money; prospek menjanjikan asal position sizing dan riset mandiri dijaga.",
    narratives: ["DeFi", "Lending", "P2P"],
  },
  {
    ticker: "MOVE", name: "Movement", slug: "movement-move", date: "2024-12-26",
    sectors: ["layer1", "infra"], category: "Altcoins Outlook · Blockchain Infrastructure",
    valuationAtReport: "$2.6B", supply: "Circ 2.2B · Max 10B",
    thesis: "Ekosistem blockchain modular berbasis bahasa Move (warisan Meta/Diem) yang memprioritaskan keamanan dan efisiensi, didukung pendanaan investor besar.",
    what: "Movement memanfaatkan bahasa Move (awalnya dari Meta untuk Diem/Libra) dengan desain modular untuk skalabilitas, interoperabilitas, dan biaya. Memakai zero-knowledge proofs. Token MOVE untuk staking, gas, governance, likuiditas DeFi.",
    bull: ["Bahasa Move menekankan keamanan aset & anti-eksploitasi kontrak", "Pendanaan mayoritas >$100 juta dari investor besar", "Arsitektur modular + ZKP", "Break market structure dengan volume tinggi pasca-listing"],
    risks: ["Proyek sangat baru (rilis 10 Des 2024), volatilitas ekstrem", "Sirkulasi hanya ~22% dari max 10B (unlock besar)", "Perlu pembuktian adopsi ekosistem nyata"],
    verdict: "Infrastruktur modular dengan teknologi Move dan pendanaan kuat; price action pasca-launch (BMS + volume tinggi) menarik dicermati.",
    narratives: ["Modular", "Move", "ZKP"],
  },
  {
    ticker: "NEAR", name: "Near Protocol", slug: "near-protocol-near", date: "2024-12-21",
    sectors: ["layer1", "ai"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$6.5B", supply: "Circ 1.2B · Max ∞",
    thesis: "Layer-1 PoS dengan sharding Nightshade yang ramah developer, diposisikan menangkap narasi AI di Q1 2025 lewat kolaborasi AI-nya.",
    what: "Near memakai PoS + sharding Nightshade (membagi chain jadi shard untuk pemrosesan paralel), mencapai ribuan TPS dengan biaya sangat rendah. Ramah developer (Rust, nama akun human-readable) dan interoperabel via Rainbow Bridge.",
    bull: ["Sharding Nightshade untuk skalabilitas tinggi", "Market cap stablecoin +21% QoQ ke ~$632 juta", "Dompet aktif tembus 2,8 juta+", "Kolaborasi AI (AI-as-a-service) untuk narasi Q1 2025"],
    risks: ["Total transaksi menurun setelah puncak awal 2024", "Max supply tak terbatas (inflasi)", "Persaingan ketat L1 (Ethereum, Solana, Avalanche)", "Jauh dari ATH $20 (Jan 2022)"],
    verdict: "Layer-1 kuat dengan basis pengguna yang terus tumbuh; kombinasi sharding dan positioning AI menjadikannya layak diperhatikan menjelang narasi AI Q1 2025.",
    narratives: ["Layer-1", "AI", "Sharding"],
  },
  {
    ticker: "ODOS", name: "ODOS", slug: "odos-odos", date: "2024-12-22",
    sectors: ["defi", "infra"], category: "Altcoins Outlook · Decentralized Exchange",
    valuationAtReport: "$57M", supply: "Circ 1.6B · Total 10B · Max 10B",
    thesis: "DEX aggregator yang menyatukan likuiditas banyak protokol untuk harga eksekusi terbaik dengan slippage dan gas minimal. Low cap baru listing CEX tier-1 dengan ruang eksposur besar bila market rally.",
    what: "Platform DEX aggregation yang menyapu likuiditas dari Uniswap, Sushiswap, Curve, Balancer, dsb. Inti teknologinya adalah smart order routing yang mencari kombinasi jalur perdagangan paling efisien untuk minimalkan gas dan dampak pasar.",
    bull: ["Baru listing di CEX tier-1 → exposure & volume baru", "Valuasi masih <$100M (low cap menarik saat rally)", "Routing optimal → harga terbaik & slippage rendah untuk trade besar", "Didukung smart money (CE Innovation, Curved Ventures, Mantle, Orbs)"],
    risks: ["Risiko inflasi dari distribusi reward komunitas besar", "Potensi sentralisasi (alokasi tim 20,4%)", "Kurang transparansi treasury & likuiditas", "Kelangsungan bergantung eksekusi tim"],
    verdict: "Low cap DEX aggregator dengan teknologi routing solid dan dukungan smart money; menarik sebagai bidak beta tinggi saat market bergerak naik.",
    narratives: ["DEX", "Aggregator", "Low Cap"],
  },
  {
    ticker: "OP", name: "Optimism", slug: "optimism-op", date: "2025-01-06",
    sectors: ["layer2"], category: "Altcoins Outlook · Layer-2",
    valuationAtReport: "$2.8B", supply: "Circ 1.3B · Total 4.2B · Max 4.2B",
    thesis: "Salah satu L2 terdepan di ekosistem Ethereum, memakai Optimistic Rollups untuk transaksi murah dan cepat sambil mewarisi keamanan Ethereum.",
    what: "Protokol Layer-2 di atas Ethereum dengan Optimistic Rollups: semua transaksi dianggap valid kecuali dibuktikan salah lewat fraud proofs. Menjaga keamanan tanpa komputasi berat per transaksi, menurunkan biaya, memudahkan integrasi aplikasi Ethereum.",
    bull: ["Salah satu solusi L2 paling matang & teradopsi", "Tokenomics pro-ekosistem (25% Ecosystem, 20% RetroPGF, 19% airdrop)", "Lonjakan aktivitas mainnet Q2 2024", "Biaya rendah & cepat menurunkan hambatan masuk"],
    risks: ["Finality lebih lama karena fraud proofs", "Persaingan ketat dengan Arbitrum & rollup zk", "zkProofs menawarkan keunggulan yang bisa menggerus daya saing"],
    verdict: "L2 blue-chip dengan fundamental dan tokenomics kuat; secara teknikal di area retest yang layak diperhatikan untuk akumulasi.",
    narratives: ["Layer-2", "Ethereum", "Rollup"],
  },
  {
    ticker: "PAAL", name: "PAAL AI", slug: "paal-ai-paal", date: "2025-01-04",
    sectors: ["ai"], category: "Altcoins Outlook · Artificial Intelligence",
    valuationAtReport: "$373M", supply: "Circ 880M · Total 1B · Max 1B",
    thesis: "Menggabungkan machine/deep learning berbasis transformer untuk solusi data prediktif real-time. Kemitraan dengan NVIDIA menjadi validasi kelas atas yang menambah daya tariknya.",
    what: "Platform AI dengan arsitektur transformer (mirip GPT/BERT) untuk mengolah data besar secara adaptif dan menghasilkan insight actionable. Menyediakan analitik lanjutan, chatbot berbasis blockchain, dan integrasi lintas aplikasi (keuangan, e-commerce, kesehatan).",
    bull: ["Kemitraan NVIDIA memberi akses teknologi mutakhir & validasi", "Menunggangi narasi AI yang makin panas 2025", "Alokasi 40% untuk liquidity provider menjaga stabilitas", "Price action berpotensi continuation menuju high Mar 2024"],
    risks: ["Alokasi 25% ke early investors berpotensi tekanan jual saat unlock", "Klaim kapabilitas AI sulit diverifikasi & rawan hype", "Sektor AI-crypto sangat volatil", "Alokasi komunitas kecil (5%)"],
    verdict: "Proyek AI dengan tie-in NVIDIA yang menonjol dan momentum narasi 2025; menarik secara price action namun butuh money management ketat.",
    narratives: ["AI", "NVIDIA", "Data"],
  },
  {
    ticker: "PYTH", name: "Pyth Network", slug: "pyth-network-pyth", date: "2024-08-19",
    sectors: ["oracle", "defi"], category: "Investing Idea · Oracle", rating: "HOLD",
    valuationAtReport: "$1.1B", supply: "Circ 3.6B · Max 10B",
    extra: [{ label: "Support kunci", value: "$3" }],
    thesis: "Oracle terdesentralisasi yang fokus pada data harga real-time paling akurat, dijuluki 'Chainlink Killer'. Teknikal di demand area ideal ($3) dengan bullish divergence untuk akumulasi.",
    what: "Jaringan oracle yang mengagregasi data harga real-time dari bursa/LP/entitas keuangan untuk dApps (crypto, saham, komoditas). Unik pada model insentif staking-akurasi: penyedia data mempertaruhkan $PYTH dan diberi imbalan sesuai akurasi.",
    bull: ["Model insentif staking-akurasi yang unik → data berkualitas", "Fokus data real-time cepat jadi keunggulan", "Permintaan naik ~17% Q2 2024 dengan lonjakan pendapatan terbesar", "Ekspansi masif: 45 feed, 14 chain, 51 aplikasi (Q2 2024)"],
    risks: ["Persaingan langsung dengan Chainlink yang jauh lebih dominan", "Max supply 10B vs circ 3.6B → tekanan emisi", "Pendapatan protokol masih kecil (~$19K Q2 2024)", "Invalidasi swing di bawah $0.21"],
    verdict: "Oracle dengan diferensiasi teknologi dan traksi on-chain meningkat; rating HOLD dengan area akumulasi ideal di sekitar support $3.",
    narratives: ["Oracle", "Data Feed", "DeFi"],
  },
  {
    ticker: "QNT", name: "Quant", slug: "quant-qnt", date: "2024-03-23",
    sectors: ["rwa", "interop"], category: "Investing Idea · Interoperability & RWA", rating: "HOLD",
    valuationAtReport: "$1.87B", supply: "Circ 14.5M · Max 14.6M",
    extra: [{ label: "Upside", value: "±300%" }, { label: "Avg 6m daily T/O", value: "$25.2M" }],
    thesis: "Menunggangi dua narasi sekaligus: tokenisasi/RWA dan CBDC. Kebutuhan bank sentral dan tradfi akan interoperabilitas blockchain memberi 'real demand' yang mendukung tesis QNT.",
    what: "Proyek interoperabilitas di persimpangan tokenisasi aset dunia nyata dan adopsi CBDC. Tokenisasi menghadirkan likuiditas/transparansi/efisiensi aset; CBDC (retail & wholesale) mendorong pembayaran lintas negara yang butuh knowledge transfer Web3.",
    bull: ["Terpapar dua narasi kuat: RWA/tokenisasi dan CBDC", "Supply langka: circ ~14.5M mendekati max 14.6M (nyaris tanpa inflasi)", "Tokenisasi diramal industri triliunan dolar", "Adopsi CBDC menciptakan real demand institusional"],
    risks: ["CBDC tersentral/privat, beda filosofi dengan crypto", "Implementasi CBDC lambat & penuh kendala teknologi", "Valuasi sudah tinggi untuk narasi yang belum termonetisasi"],
    verdict: "Bidak interoperabilitas langka-supply yang menjembatani narasi RWA dan CBDC; rating HOLD dengan potensi upside ~300% bila narasi termaterialisasi.",
    narratives: ["CBDC", "Tokenisasi", "RWA"],
  },
  {
    ticker: "RIO", name: "Realio Network", slug: "realio-rio", date: "2024-12-22",
    sectors: ["rwa", "interop"], category: "Altcoins Outlook · Real World Assets",
    valuationAtReport: "$48M", supply: "Circ 50M · Total 50M · Max 175M",
    thesis: "Micro cap RWA yang memfasilitasi tokenisasi sekuritas digital dan real estate dengan fokus kepatuhan regulasi. Menarik bila narasi RWA kembali bersinar Q2 2025.",
    what: "Ekosistem blockchain hybrid untuk tokenisasi aset dunia nyata (properti, ekuitas, obligasi) dengan interoperabilitas lintas jaringan (Ethereum, Algorand, Stellar). Token $RIO dibakar saat tokenisasi, staking market maker, reward node, dan terintegrasi DeFi.",
    bull: ["Micro cap RWA (~$48M) dengan ruang naik besar bila narasi panas", "Alokasi 50% STO menandakan fokus penggalangan patuh regulasi", "Interoperabilitas multi-chain memperluas akses aset", "Big caps RWA sudah rally → peluang rotasi ke low caps"],
    risks: ["Risiko sentralisasi (alokasi STO besar bisa terkonsentrasi)", "Alokasi tim 9,5% tanpa vesting jelas", "Tidak ada alokasi khusus marketing/ekosistem", "Gap supply besar (max 175M vs circ 50M)"],
    verdict: "Micro cap RWA dengan kerangka tokenisasi kuat namun perlu perhatian pada sentralisasi & pengembangan ekosistem; taruhan beta pada narasi RWA 2025.",
    narratives: ["RWA", "Tokenisasi", "Micro Cap"],
  },
  {
    ticker: "RUNE", name: "THORChain", slug: "thorchain-rune", date: "2025-01-04",
    sectors: ["interop", "defi"], category: "Altcoins Outlook · Cross-Chain",
    valuationAtReport: "$1.7B", supply: "Circ 341M · Total 416M · Max 500M",
    thesis: "Protokol likuiditas terdesentralisasi yang memungkinkan swap aset native lintas blockchain tanpa wrapped token atau perantara. Kombinasi cross-chain unik dengan potensi koreksi untuk entry.",
    what: "Layer-1 berbasis Cosmos SDK (konsensus Tendermint) yang memakai cross-chain liquidity pool dan AMM untuk menukar aset native (BTC, ETH, BNB) langsung tanpa kehilangan kepemilikan di rantai asal. Diamankan node validator multi-signature.",
    bull: ["Swap aset native lintas rantai tanpa wrapped token (diferensiasi unik)", "Mendukung banyak chain besar (BTC, ETH, BSC, DOGE, SOL)", "40% RUNE di-bond node operator → keamanan via staking", "34,2% RUNE di liquidity pools → fokus likuiditas"],
    risks: ["Model ekonomi bergantung bonded RUNE; riwayat exploit jadi sorotan", "Weekly chart potensi koreksi jangka pendek", "Persaingan solusi interoperabilitas makin ramai", "Emisi lanjutan (max 500M vs circ 341M)"],
    verdict: "Protokol cross-chain dengan moat native-swap yang jelas; menarik diakumulasi memanfaatkan potensi koreksi pada weekly chart.",
    narratives: ["Cross-Chain", "DeFi", "Interoperability"],
  },
  {
    ticker: "SEI", name: "Sei", slug: "sei-sei", date: "2024-08-19",
    sectors: ["layer1", "defi"], category: "Investing Idea · Layer-1", rating: "HOLD",
    valuationAtReport: "$1.1B", supply: "Circ 3.3B · Max 10B",
    thesis: "Layer-1 paralel yang DeFi-friendly dengan finality tercepat (di bawah satu detik) berkat parallelization. Teknikal di demand area konsolidasi yang ideal untuk akumulasi.",
    what: "Blockchain Layer-1 berbasis Cosmos SDK, fokus transaksi keuangan cepat, murah, latensi rendah. Inovasinya: parallelization yang meningkatkan throughput dibanding blockchain sekuensial, menghasilkan finality tercepat di antara peer (per Binance Research).",
    bull: ["Finality di bawah satu detik, tercepat vs Aptos/Sui/Solana/AVAX", "Arsitektur paralel → throughput tinggi", "TVL naik masif awal 2024 (~33% QoQ), DeFi nyata", "Upgrade Sei V2 menghadirkan kompatibilitas EVM"],
    risks: ["Blockchain paralel butuh pengamanan ekstra (kompleks)", "Aktivitas & harga turun drastis Q3 2024", "Max supply 10B vs circ 3.3B → tekanan emisi besar", "Persaingan sengit antar L1 baru"],
    verdict: "Layer-1 paralel dengan fundamental DeFi nyata dan finality kelas atas; rating HOLD dengan area akumulasi ideal di zona konsolidasi demand.",
    narratives: ["Layer-1", "Parallel Chain", "DeFi"],
  },
  {
    ticker: "SPEC", name: "Spectral", slug: "spectral-spec", date: "2024-12-06",
    sectors: ["ai", "infra"], category: "Altcoins Outlook · Artificial Intelligence",
    valuationAtReport: "$205M", supply: "Circ 14M · Total 100M · Max 100M",
    thesis: "Infrastruktur untuk membuat AI Agents otonom on-chain lewat bahasa alami. Tesisnya: memegang infrastruktur tempat agen dibangun lebih realistis daripada menebak agen individual yang menang.",
    what: "Platform (Spectral Syntax) yang mengubah instruksi bahasa alami jadi kode Solidity via LLM khusus, lalu men-deploy AI Agent on-chain dengan beberapa klik. Agen berjalan mandiri: akses feed data, analisis peristiwa, eksekusi strategi; punya token native.",
    bull: ["Investasi pada infrastruktur, bukan produk tunggal, dari maraknya AI Agents", "Menunggangi narasi AI-crypto menuju puncak Q1 2025", "Twitter followers meledak 10K → 174K (Jun-Des 2024)", "Supply beredar sangat kecil (14M) → sensitivitas harga tinggi"],
    risks: ["Circ hanya 14M dari max 100M → unlock bisa menekan harga", "Narasi AI Agents rawan hype & koreksi tajam", "Kompetisi platform AI Agent cepat bertambah", "Volatilitas sangat tinggi"],
    verdict: "Bidak infrastruktur AI Agent dengan momentum sosial & volume kuat; menarik sebagai key player narasi AI namun dengan risiko unlock dan hype yang perlu dikelola.",
    narratives: ["AI Agents", "Infrastructure", "On-Chain AI"],
  },
  {
    ticker: "STX", name: "Stacks", slug: "stacks-stx", date: "2024-12-05",
    sectors: ["layer2", "layer1"], category: "Altcoins Outlook · Bitcoin Layer",
    valuationAtReport: "$4.3B", supply: "Circ 1.5B · Total 1.5B · Max 1.8B",
    thesis: "Membawa smart contract dan DApps ke ekosistem Bitcoin lewat Proof of Transfer. Nakamoto Upgrade yang menjadikannya trustless Bitcoin layer adalah katalis utama siklus ini.",
    what: "Blockchain L1/L2 yang memperluas Bitcoin dengan smart contract. Konsensus Proof of Transfer (PoX): penambang pakai BTC untuk buat blok Stacks dan terima STX; stacker mengunci STX ('stacking') untuk reward BTC tanpa slashing. Bahasa Clarity aman & auditable.",
    bull: ["Nakamoto Upgrade → trustless Bitcoin layer (katalis besar)", "Membawa DeFi/NFT/tokenisasi ke ekosistem Bitcoin", "Stacking memberi yield BTC tanpa risiko slashing", "Harga & TVL bergerak naik seirama, peluang tembus >$4"],
    risks: ["Volume perdagangan masih kecil dibanding puncak awal 2024", "Aktivitas jaringan menurun tajam setelah Q1 2024", "Tren pendapatan jaringan menurun hingga Q3 2024"],
    verdict: "Bitcoin layer dengan fondasi kuat dan katalis Nakamoto Upgrade yang jelas; berpotensi jadi aset penting siklus ini asalkan mampu memulihkan momentum pengguna.",
    narratives: ["Bitcoin L2", "Smart Contract", "Nakamoto"],
  },
  {
    ticker: "SUPRA", name: "Supra", slug: "supra-supra", date: "2025-01-04",
    sectors: ["oracle", "infra"], category: "Altcoins Outlook · Oracles",
    valuationAtReport: "$236M", supply: "Circ 6B · Total 79B · Max 100B",
    thesis: "Oracle generasi baru yang mengklaim data lebih cepat, aman, dan murah dari Chainlink lewat fast consensus dan threshold cryptography. Didukung investor ternama, konsolidasi dengan potensi bullish continuation.",
    what: "Platform oracle yang menyediakan data real-time latensi rendah untuk banyak blockchain. Memakai fast consensus (proses ribuan data/detik) dan threshold cryptography (data hanya dapat diakses node berwenang), klaim biaya operasional lebih rendah.",
    bull: ["Klaim salah satu oracle tercepat dengan biaya rendah", "Threshold cryptography tahan man-in-the-middle & manipulasi harga", "Didukung Coinbase Ventures, Galaxy Interactive, Hashkey", "Price action naik >8x sejak listing, konsolidasi → potensi continuation"],
    risks: ["Supply sangat inflatif: circ 6B dari max 100B", "Bersaing langsung melawan Chainlink yang dominan", "Klaim performa oracle masih perlu pembuktian adopsi", "Sudah naik >8x → risiko koreksi"],
    verdict: "Oracle menjanjikan dengan backer kuat dan momentum harga, namun overhang supply 100B jadi risiko utama; pantau untuk bullish continuation dengan disiplin risiko.",
    narratives: ["Oracle", "Data Feed", "Cross-Chain"],
  },
  {
    ticker: "THETA", name: "Theta Network", slug: "theta-network-theta", date: "2024-12-30",
    sectors: ["depin", "data"], category: "Altcoins Outlook · Entertainment on Blockchain",
    valuationAtReport: "$2.2B", supply: "Circ 1B · Max 1B",
    thesis: "Memanfaatkan blockchain untuk mendesentralisasi distribusi video dan streaming, memangkas biaya bandwidth lewat jaringan berbagi sumber daya peer-to-peer.",
    what: "Blockchain khusus media/hiburan yang membiarkan pengguna menyumbang bandwidth & komputasi P2P untuk mengirim konten lebih efisien. Punya Theta Virtual Machine (TVM) untuk membangun dApps (monetisasi konten, voting penggemar, NFT).",
    bull: ["Kemitraan besar: Google (validator node), Samsung, Sony, Twitch", "Volume transaksi 2024 memuncak mendekati 2 miliar", "Sharpe ratio stabil ~1,32 (profil risk-return positif)", "Use case nyata di esports, hiburan, pendidikan"],
    risks: ["Sektor streaming terdesentralisasi masih niche & kompetitif", "Bergantung kelanjutan adopsi & momentum ekosistem media"],
    verdict: "Proyek media/streaming berbasis blockchain dengan aktivitas jaringan kuat dan mitra korporat besar; menarik saat chart weekly koreksi menjelang potensi kelanjutan.",
    narratives: ["Streaming", "Media"],
  },
  {
    ticker: "TIA", name: "Celestia", slug: "celestia-tia", date: "2024-10-25",
    sectors: ["infra", "layer1"], category: "Altcoins Outlook · Modular",
    valuationAtReport: "$1.3B", supply: "Circ 219M · Max ∞",
    thesis: "Mempelopori modular blockchain dengan memisahkan konsensus, eksekusi, dan ketersediaan data agar jaringan lebih skalabel tanpa mengorbankan keamanan.",
    what: "Layer data-availability modular yang memisahkan fungsi blockchain ke lapisan terpisah (berbeda dari arsitektur monolitik). Konsensus Tendermint (finality 15 detik) dengan data availability sampling agar node cek ketersediaan data tanpa unduh seluruh blok.",
    bull: ["Finality tercepat di kelasnya (15 detik) + fraud proofs", "Data posting melonjak pasca Dencun & Eclipse mainnet (~3.500/hari)", "Alokasi 26,8% untuk R&D mendukung inovasi jangka panjang", "Distribusi token merata"],
    risks: ["Alokasi early investor tinggi (19,7% + 15,9%) → tekanan jual", "Kontributor inti pegang kendali besar (17,6%)", "Unlock besar akhir Okt 2024 jadi risiko sekaligus katalis"],
    verdict: "Salah satu proyek modular/DA terdepan dengan fundamental teknis kuat; weekly breakout dengan area akumulasi ideal, sizing maks 3% untuk hold jangka panjang.",
    narratives: ["Modular", "Data Availability"],
  },
  {
    ticker: "TON", name: "Toncoin", slug: "the-open-network-ton", date: "2024-12-21",
    sectors: ["layer1"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$13B", supply: "Circ 2.5B · Max ∞",
    thesis: "Layer-1 cepat dan skalabel dengan keunggulan unik: akses ke 800+ juta pengguna Telegram sebagai jalur onboarding massal ke blockchain.",
    what: "Blockchain layer-1 PoS yang awalnya dibangun tim Telegram, kini dikembangkan komunitas open-source. Memakai sharding untuk membagi beban transaksi ke subchain dan mendukung interoperabilitas antar-blockchain.",
    bull: ["Basis pengguna Telegram ~900 juta MAU sebagai funnel adopsi", "Hanya butuh penetrasi ~5% Telegram untuk lampaui MAU ETH+SOL", "Daily Active Addresses melampaui Ethereum sejak Jun 2024", "Branding kuat warisan Telegram"],
    risks: ["Overhang hukum: penangkapan Pavel Durov menekan TVL & harga", "Telegram tak lagi resmi terkait pengembangan TON", "Sensitif terhadap sentimen berita fundamental di luar kontrol"],
    verdict: "Layer-1 dengan potensi adopsi terbesar berkat Telegram; jika isu fundamental Durov membaik, bisa jadi salah satu jaringan terbesar di crypto.",
    narratives: ["Telegram", "Mass Adoption"],
  },
  {
    ticker: "TRX", name: "Tron", slug: "tron-trx", date: "2024-07-09",
    sectors: ["layer1", "payments"], category: "Investing Idea · Layer-1", rating: "HOLD",
    valuationAtReport: "$10B", supply: "Circ 86B · Max ∞",
    extra: [{ label: "Target", value: "$0.25+" }],
    thesis: "Dianggap layer-1 paling undervalued karena perannya sebagai rel utama peredaran USDT, dengan fundamental jaringan lebih kuat dari yang dipersepsikan pasar.",
    what: "Blockchain layer-1 yang mendominasi transfer stablecoin, khususnya USDT. Meski dicap 'koin dinosaurus', metriknya unggul: daily fees dan active users tertinggi dibanding BNB, Solana, atau Avalanche.",
    bull: ["78% aktivitas jaringan Q2 2024 untuk transfer USDT (~2 juta tx/hari)", "Daily fees & active users tertinggi di antara L1 pesaing", "FDMC terendah sejak launch = valuasi relatif murah", "Founder Justin Sun agresif berinovasi"],
    risks: ["Utilitas terkonsentrasi pada satu fungsi (transfer USDT)", "Risiko kunci terkait figur sentral Justin Sun", "Invalidasi teknikal di bawah $0.1"],
    verdict: "Layer-1 undervalued dengan naratif, teknikal, dan fundamental menarik; ascending triangle di monthly chart, target $0.25+, exposure maks 10% portofolio.",
    narratives: ["Stablecoin Rail", "Undervalued"],
  },
  {
    ticker: "VANA", name: "Vana", slug: "vana-vana", date: "2024-12-21",
    sectors: ["ai", "data"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$572M", supply: "Circ 30.8M · Max 120M",
    thesis: "Layer-1 EVM yang mengubah data pribadi pengguna menjadi aset finansial untuk melatih model AI, lewat Data DAOs dan Data Liquidity Pools.",
    what: "Blockchain layer-1 EVM-compatible berfokus pada kepemilikan & monetisasi data. Pengguna menyumbang data terenkripsi ke Data Liquidity Pools (DLP), divalidasi lewat Proof of Contribution, ditokenisasi, lalu dibeli peneliti ML via API.",
    bull: ["Naratif kuat di persilangan AI dan data ownership", "Alokasi komunitas besar (40%) mendorong adopsi", "Model unik memberi pengguna kontrol & monetisasi data", "Layer-1 EVM-compatible memudahkan integrasi"],
    risks: ["Alokasi kontributor inti + investor gabungan 33% → tekanan jual", "Token baru volatil (ATH $33 lalu sell-off)", "Model bisnis data-untuk-AI belum terbukti skala besar"],
    verdict: "Proyek layer-1 EVM dengan tesis data-AI yang menarik namun masih early; price action klasik listing baru yang butuh konsolidasi.",
    narratives: ["AI Data", "DataFi"],
  },
  {
    ticker: "VET", name: "VeChain", slug: "vechain-vet", date: "2024-12-26",
    sectors: ["layer1", "rwa"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$4B", supply: "Circ 80B · Max 86B",
    extra: [{ label: "Sharpe Ratio", value: "2.25" }],
    thesis: "Layer-1 enterprise yang fokus pada transparansi dan efisiensi rantai pasok, memadukan blockchain dengan perangkat IoT.",
    what: "Platform blockchain untuk kebutuhan bisnis & supply chain, berjalan di VeChainThor dengan konsensus Proof of Authority (PoA) hemat energi. Mengintegrasikan IoT (sensor, RFID) untuk pelacakan aset real-time; menawarkan ToolChain (SaaS) bagi perusahaan.",
    bull: ["Fokus enterprise nyata di supply chain dengan kemitraan korporat", "Sharpe ratio 2.25 (imbal hasil baik dengan risiko terkelola)", "Volume perdagangan melonjak akhir 2024", "PoA efisien + governance internal cepat"],
    risks: ["Model PoA dianggap kurang terdesentralisasi", "Bergantung adopsi korporat yang lambat", "Kinerja harga sangat bergantung rally market keseluruhan"],
    verdict: "Layer-1 enterprise dengan fundamental supply chain kuat; chart bulanan retest dengan potensi continuation jika market rally.",
    narratives: ["Supply Chain", "Enterprise"],
  },
  {
    ticker: "VISTA", name: "EtherVista", slug: "ethervista-vista", date: "2024-12-24",
    sectors: ["defi"], category: "Altcoins Outlook · Decentralized Exchange",
    valuationAtReport: "$23M", supply: "Circ 961K · Max 1M",
    thesis: "DEX di Ethereum dengan model fee unik berbasis ETH yang dibagi ke penyedia likuiditas dan pencipta token, memposisikan diri sebagai 'pump.fun'-nya Ethereum.",
    what: "Decentralized exchange dengan pendekatan berbeda dari AMM tradisional: biaya transaksi dibayar dalam ETH lalu didistribusikan ke LP dan developer token. Fitur: liquidity lock 5 hari anti-rug, flash loans, futures, lending, SuperChat.",
    bull: ["Mekanisme fee ETH memberi insentif kuat ke LP & token creator", "Liquidity lock 5 hari mengurangi risiko rug pull", "Model deflationary: circulating supply terus menurun", "Potensi jadi platform peluncuran token di Ethereum"],
    risks: ["Platform sangat baru dengan TVL fluktuatif ($6M puncak, kini $3M)", "Market cap kecil ($23M) → likuiditas & volatilitas ekstrem", "Bergantung tren 'launchpad' yang belum terbukti bertahan"],
    verdict: "DEX inovatif bermodel deflationary yang bisa berharga jika berhasil menghadirkan 'pump.fun' di Ethereum; masih fase awal dan spekulatif.",
    narratives: ["DEX", "Launchpad"],
  },
  {
    ticker: "W", name: "Wormhole", slug: "wormhole-w", date: "2024-05-04",
    sectors: ["interop"], category: "Altcoins Outlook · Cross-Chain Bridge",
    valuationAtReport: "$2.5B",
    thesis: "Protokol cross-chain bridge yang menghubungkan puluhan jaringan blockchain agar bisa saling berkomunikasi dan mentransfer aset, menyelesaikan masalah interoperabilitas.",
    what: "Protokol bridging antar-blockchain yang memfasilitasi transaksi DeFi & NFT lintas rantai lewat 30+ jaringan. Diamankan 19 'Wormhole Guardian' node yang memvalidasi setiap transaksi; token W juga governance.",
    bull: ["Didanai nama besar: Coinbase Ventures, $225M pada valuasi $2.5B", "Ekspansi luas ke 30+ jaringan termasuk L2 Ethereum", "Tekanan jual airdrop (617M token) diperkirakan mereda", "Tim berpengalaman (founder eks-Jump Crypto)"],
    risks: ["Bridge adalah target peretasan bernilai tinggi di crypto", "Bergantung keamanan 19 Guardian node", "Oscillator daily belum siap, waspada potensi 'grab'"],
    verdict: "Proyek interoperabilitas mapan dengan pendanaan & jaringan kuat; daily chart bullish ChoCh dengan S&R flip di $0.7, cocok strategi multiple entries.",
    narratives: ["Bridge", "Interoperability"],
  },
  {
    ticker: "XMR", name: "Monero", slug: "monero-xmr", date: "2024-12-04",
    sectors: ["privacy"], category: "Altcoins Outlook · Privacy",
    valuationAtReport: "$3.7B", supply: "Circ 18.4M · Max ∞",
    thesis: "Cryptocurrency privasi terkemuka yang menyembunyikan pengirim, penerima, dan jumlah transaksi, dengan permintaan yang konsisten dan revenue terus tumbuh.",
    what: "Blockchain fokus privasi/anonimitas yang memakai ring signatures, stealth addresses, dan RingCT agar transaksi tak terlacak. Fungible, PoW yang bisa ditambang CPU/GPU, dikelola komunitas open-source sukarela.",
    bull: ["Use case privasi yang nyata & terus dibutuhkan", "Revenue protokol konsisten naik (<$100M 2018 → ~$570M 2025)", "Konsolidasi panjang mirip pola koin lama (XRP, XLM) sebelum rally", "Fungible & mining inklusif (CPU/GPU)"],
    risks: ["Tekanan regulasi berat; sering di-delist karena isu privasi", "Valuasi sudah besar → upside kelipatan lebih berat", "Ukuran blockchain lebih besar karena mekanisme privasi"],
    verdict: "Proyek privasi 'sehat' dengan revenue konsisten dan naratif privasi menguat; valuasi besar membatasi upside namun tetap menarik di masa euforia altcoin.",
    narratives: ["Privacy", "Fungibility"],
  },
  {
    ticker: "XTZ", name: "Tezos", slug: "tezos-xtz", date: "2024-12-29",
    sectors: ["layer1"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$1.4B", supply: "Circ 1B · Max ∞",
    thesis: "Layer-1 dengan governance on-chain yang bisa memperbarui protokol tanpa hard fork, didukung tren pertumbuhan aktivitas jaringan dan stablecoin.",
    what: "Platform blockchain untuk smart contract & dApps dengan Liquid Proof-of-Stake (baking + delegasi). Smart contract ditulis dalam Michelson yang mendukung verifikasi formal untuk keamanan aplikasi keuangan.",
    bull: ["Governance on-chain menghindari hard fork yang memecah komunitas", "TVL stablecoin naik, dominasi USDT 68% → 75%", "Aktivitas jaringan naik 46% QoQ Q3 2024", "Verifikasi formal Michelson unggul untuk DeFi/keamanan"],
    risks: ["Persaingan layer-1 sangat ketat, relevansi menurun", "Butuh peningkatan adopsi nyata agar nilai pasar naik", "Pertumbuhan bergantung ekspansi NFT & DeFi berbasis Tezos"],
    verdict: "Layer-1 mapan dengan governance unik dan aktivitas jaringan meningkat; weekly chart koreksi dengan potensi kelanjutan kenaikan jika adopsi bertambah.",
    narratives: ["On-chain Governance", "Self-amending"],
  },
  {
    ticker: "ZENT", name: "Zentry", slug: "zentry-zent", date: "2024-12-24",
    sectors: ["gaming"], category: "Altcoins Outlook · GameFi",
    valuationAtReport: "$190M", supply: "Circ 6B · Max 10B",
    thesis: "Proyek GameFi (eks-GuildFi) yang menyatukan game Web2, Web3, dan aktivitas sosial dunia nyata, memberi reward lintas platform lewat token ZENT.",
    what: "Ekosistem gaming-finance hasil rebranding GuildFi (Apr 2024). Komponen: Metagame Layer (identitas/reputasi/loyalitas pemain), Radiant (reward lintas media sosial & acara fisik), dan Play Economy untuk in-game & out-game.",
    bull: ["Total supply dibatasi + burn mechanism (deflationary)", "Menawarkan reward staking dan ekonomi in-game + out-game", "Volume naik signifikan dengan lonjakan besar Des 2024", "Sharpe ratio naik Okt-Des 2024; fase pre-breakout"],
    risks: ["Circulating supply besar (6B) dengan max 10B → risiko dilusi", "Proyek baru rilis, adopsi & retensi belum terbukti", "Sektor GameFi historis volatil & hype-driven"],
    verdict: "GameFi listing baru yang menarik dengan tokenomics deflationary; market cenderung mendukung proyek baru menjelang katalis gaming, tapi masih spekulatif.",
    narratives: ["GameFi", "New Listing"],
  },
  {
    ticker: "ZRO", name: "LayerZero", slug: "layerzero-zro", date: "2024-10-24",
    sectors: ["interop", "infra"], category: "Altcoins Outlook · Interoperability",
    valuationAtReport: "$416M", supply: "Circ 111M · Max 1B",
    extra: [{ label: "OApps", value: "54.6K" }],
    thesis: "Protokol interoperabilitas omnichain yang menghubungkan berbagai blockchain untuk transfer data dan aset, dengan mindshare rendah yang dianggap value terpendam.",
    what: "Protokol infrastruktur cross-chain yang memungkinkan blockchain berkomunikasi & bertukar aset lewat LZ Endpoint, MessageLib, DVN (validator terdistribusi), dan Executor. Token ZRO didistribusikan lewat 'Proof-of-Donation'.",
    bull: ["Q2 2024 tambah 12 jaringan baru, fasilitasi transfer ~$5 miliar", "OApps tumbuh 8,6K → 54,6K (Q2 2023→2024)", "Nilai rata-rata per pesan naik 78,2% ($227 → $405)", "Didanai smart money banyak (a16z, Samsung Next, Franklin Templeton)"],
    risks: ["Alokasi 57% ke mitra & kontributor inti (kesan 'barang VC')", "Potensi price impact dari konsentrasi kepemilikan", "Mindshare pasar sedang rendah meski teknologi penting"],
    verdict: "Infrastruktur omnichain penting dengan adopsi OApps pesat dan backing VC kelas atas; weekly berpeluang rebound, sizing maks 3%.",
    narratives: ["Omnichain", "Interoperability"],
  },

  // ── Batch 2: Dec 2024 – Feb 2025 reports ──
  {
    ticker: "AIOZ", name: "AIOZ Network", slug: "aioz-network-aioz", date: "2025-01-02",
    sectors: ["depin", "infra", "ai"], category: "Altcoins Outlook · DePIN",
    valuationAtReport: "$900M", supply: "Circ 1.1B · Total 1.1B · Max ∞",
    thesis: "Layer-1 DePIN yang mendesentralisasi distribusi dan penyimpanan konten lewat jaringan dCDN peer-to-peer, memakai hardware pengguna sebagai node.",
    what: "AIOZ membangun Decentralized Content Delivery Network (dCDN) untuk menggantikan CDN tradisional yang mahal & terpusat. Lewat arsitektur P2P dan edge computing, perangkat pengguna biasa menyumbang storage & bandwidth. Token $AIOZ jadi insentif: bayar layanan sekaligus reward node.",
    bull: ["Menyasar pasar CDN/streaming besar dengan biaya lebih murah", "Tokenomics memutar insentif langsung ke penyedia node", "Masuk narasi DePIN + AI yang kuat", "Komunitas tumbuh (follower +50% setahun)"],
    risks: ["Persaingan ketat CDN Web2 raksasa yang matang", "Max supply tak terbatas (∞) → tekanan nilai jangka panjang", "Adopsi sebagai infrastruktur produksi masih harus dibuktikan"],
    verdict: "Proyek DePIN dengan use-case jelas dan komunitas berkembang; menarik untuk thesis jangka panjang, dengan area retest ~$0.75 sebagai zona akumulasi, tapi waspadai supply tak terbatas.",
    narratives: ["DePIN", "AI", "CDN", "Storage"],
  },
  {
    ticker: "GRT", name: "The Graph", slug: "the-graph-grt", date: "2025-01-01",
    sectors: ["data", "infra"], category: "Altcoins Outlook · Blockchain Infrastructure",
    valuationAtReport: "$1.9B", supply: "Circ 9B · Total/Max 10.7B",
    extra: [{ label: "Kueri Q3 2024", value: "5,3 miliar (+79% QoQ)" }],
    thesis: "Protokol pengindeksan terdesentralisasi ('Google-nya Web3') yang membuat data blockchain bisa dikueri lewat subgraphs — infrastruktur inti bagi dApps.",
    what: "The Graph mengorganisir & menyediakan akses data on-chain lewat API terbuka (subgraphs) tanpa server terpusat. Ekosistem: Indexers (operator node yang staking & melayani kueri) dan Delegators (holder $GRT yang mendelegasikan token). $GRT untuk staking, signaling, dan biaya kueri.",
    bull: ["Volume kueri meledak 79% QoQ ke 5,3 miliar (Q3 2024)", "Query fees naik 83% QoQ → model bisnis berkorelasi penggunaan", "Infrastruktur fundamental hampir semua dApp/DeFi Web3", "Peran Indexer/Delegator menciptakan permintaan staking"],
    risks: ["Kompetitor indexing terpusat yang lebih cepat/murah", "Pendapatan absolut masih kecil relatif valuasi miliaran", "Bergantung pertumbuhan ekosistem Web3", "Tekanan emisi dari selisih circ vs total"],
    verdict: "Salah satu infrastruktur data Web3 paling mapan dengan metrik penggunaan yang tumbuh sehat; fundamental kuat meski monetisasi absolut masih perlu skala.",
    narratives: ["Data", "Web3", "Indexing", "Subgraph"],
  },
  {
    ticker: "FET", name: "Artificial Superintelligence Alliance", slug: "artificial-superintelligence-alliance-fet", date: "2025-01-01",
    sectors: ["ai"], category: "Altcoins Outlook · Artificial Intelligence",
    valuationAtReport: "$3.2B", supply: "Circ 2.6B · Total/Max 2.7B",
    extra: [{ label: "Basis", value: "Merger Fetch.ai + ekosistem AI (ASI Alliance)" }],
    thesis: "Proyek AI yang menggabungkan agen AI otonom, blockchain PoS, dan IoT untuk menciptakan ekonomi mesin-ke-mesin tanpa perantara.",
    what: "Dikembangkan Fetch.ai di bawah Artificial Superintelligence Alliance. $FET memungkinkan Autonomous Economic Agents (AEA) — agen AI yang berinteraksi & menjalankan tugas mandiri. Memakai PoS dan Open Economic Framework (OEF). Narasi AI+AI-agents sedang memuncak masuk Q1 2025.",
    bull: ["Diuntungkan langsung narasi AI & AI-agent paling panas 2025", "Merger ASI menyatukan beberapa proyek AI besar", "Listing bursa besar (Binance) → likuiditas & eksposur", "Framework OEF + agen otonom sebagai diferensiasi"],
    risks: ["Persaingan sengit AI crypto & AI terpusat (Big Tech)", "Kompleksitas tinggi; adopsi agen AI belum terbukti masif", "Valuasi sudah premium ($3.2B) → sensitif sentimen", "Risiko integrasi pasca-merger"],
    verdict: "Pemimpin kategori AI-crypto dengan momentum narasi kuat dan ekosistem gabungan; potensi besar tapi valuasi sudah memperhitungkan ekspektasi tinggi.",
    narratives: ["AI", "AI Agents", "IoT"],
  },
  {
    ticker: "ALGO", name: "Algorand", slug: "algorand-algo", date: "2025-01-01",
    sectors: ["layer1"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$2.6B", supply: "Circ 8.3B · Total 8.3B · Max 10B",
    thesis: "Layer-1 Pure PoS bikinan Silvio Micali (MIT, Turing Award) yang menargetkan solusi blockchain trilemma dengan finalitas cepat dan hemat energi.",
    what: "Algorand (2019) memakai Pure Proof-of-Stake di mana semua holder bisa ikut validasi — menjaga desentralisasi sekaligus efisiensi. Konfirmasi <5 detik, throughput tinggi. dApps via Algorand Virtual Machine (AVM). Ekosistem menyasar stablecoin, tokenisasi aset, dan institusi.",
    bull: ["PPoS matang dengan finalitas cepat (<5 detik) & hemat energi", "Kredibilitas akademis kuat (pemenang Turing Award MIT)", "Fokus institusi/RWA & tokenisasi aset", "Desain hemat sumber daya untuk aplikasi kompleks"],
    risks: ["Kalah momentum/mindshare dibanding L1 lain meski teknologi solid", "Ekosistem DeFi/dApp relatif tipis", "Ketergantungan narasi RWA/institusi yang lambat", "Selisih total vs max (8.3B→10B) → potensi emisi"],
    verdict: "L1 dengan fundamental teknis kuat dan pedigree akademis, tapi tertinggal dalam mindshare & aktivitas ekosistem; tesisnya bertumpu pada adopsi institusi/RWA jangka panjang.",
    narratives: ["Layer-1", "PPoS", "RWA", "Institutional"],
  },
  {
    ticker: "APT", name: "Aptos", slug: "aptos-apt", date: "2025-01-01",
    sectors: ["layer1"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$5B", supply: "Circ 557M · Total 1.1B · Max ∞",
    extra: [{ label: "Bahasa", value: "Move (warisan proyek Diem/Meta)" }],
    thesis: "Layer-1 'blue chip' berperforma tinggi warisan tim Diem (Meta), memakai bahasa Move dan eksekusi paralel untuk throughput ribuan TPS.",
    what: "Aptos (2022) dibangun eks-tim Diem milik Meta, memakai bahasa Move yang menekankan keamanan & efisiensi. Eksekusi transaksi paralel memungkinkan ribuan TPS dengan finalitas cepat, bersaing dengan Solana & Avalanche. Tooling ramah developer + backing institusi besar.",
    bull: ["Performa tinggi (ribuan TPS) via eksekusi paralel", "Bahasa Move memberi keamanan smart contract lebih baik", "Warisan teknologi & talenta dari Diem/Meta", "Dukungan kuat investor institusional & ekosistem developer aktif"],
    risks: ["Max supply tak terbatas (∞) + circ rendah → tekanan unlock/emisi", "Persaingan L1 high-performance sangat sengit (Solana, Sui)", "Valuasi tinggi ($5B) dengan ekosistem masih muda", "Konsentrasi kepemilikan awal (VC/tim)"],
    verdict: "L1 high-performance dengan tim & teknologi kelas atas serta backing institusi kuat; katalis positif tapi waspadai skema supply tak terbatas dan tekanan unlock.",
    narratives: ["Layer-1", "Move", "High-performance", "Institutional"],
  },
  {
    ticker: "ADA", name: "Cardano", slug: "cardano-ada", date: "2024-12-31",
    sectors: ["layer1"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$30B", supply: "Circ 35B · Total/Max 45B",
    extra: [{ label: "Konsensus", value: "Ouroboros (PoS)" }],
    thesis: "Layer-1 PoS bikinan Charles Hoskinson dengan pendekatan ilmiah peer-reviewed, menekankan keamanan, desentralisasi, dan keberlanjutan.",
    what: "Cardano (2017) dibangun co-founder Ethereum, Charles Hoskinson, dengan filosofi pengembangan berbasis riset akademik peer-reviewed. Memakai konsensus PoS Ouroboros untuk infrastruktur aman, terdesentralisasi, hemat energi. Menargetkan adopsi jangka panjang lewat pendekatan bertahap & teruji.",
    bull: ["Pendekatan riset peer-reviewed → reputasi keamanan jangka panjang", "Komunitas & basis holder sangat besar dan loyal", "Konsensus Ouroboros yang matang & hemat energi", "Kapitalisasi besar & likuiditas tinggi sebagai L1 mapan"],
    risks: ["Pengembangan lambat/metodis sering dianggap tertinggal adopsi dApp", "Aktivitas DeFi/TVL relatif kecil vs kapitalisasi $30B", "Persaingan L1 smart contract makin padat", "Valuasi tinggi → upside terbatas tanpa lonjakan adopsi"],
    verdict: "L1 blue-chip dengan fondasi ilmiah & komunitas kuat, namun valuasi besar tidak sejalan dengan aktivitas on-chain; tesisnya menuntut percepatan adopsi nyata.",
    narratives: ["Layer-1", "PoS", "Peer-reviewed", "Ouroboros"],
  },
  {
    ticker: "DOT", name: "Polkadot", slug: "polkadot-dot", date: "2024-12-31",
    sectors: ["layer1", "interop"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$10B", supply: "Circ 1.5B · Total 1.5B · Max ∞",
    extra: [{ label: "Arsitektur", value: "Relay chain + parachain" }],
    thesis: "Platform multi-chain bikinan Gavin Wood (co-founder Ethereum) yang fokus pada interoperabilitas dan skalabilitas via mekanisme parachain.",
    what: "Polkadot (2020) mengatasi isolasi jaringan & keterbatasan skalabilitas lewat arsitektur multi-chain. Parachain (blockchain independen paralel) terhubung ke relay chain pusat untuk keamanan & interoperabilitas bersama. Token $DOT untuk staking, governance, dan bonding slot parachain.",
    bull: ["Solusi interoperabilitas kuat lewat parachain + shared security", "Didirikan Gavin Wood (kredibilitas Substrate/Web3 Foundation)", "Framework Substrate memudahkan peluncuran chain baru", "Governance on-chain & roadmap (JAM) ambisius"],
    risks: ["Model lelang slot parachain kompleks & adopsi melambat", "Max supply tak terbatas (∞) via inflasi staking", "Mindshare menurun dibanding L1/L2 pesaing", "Kompleksitas ekosistem menyulitkan onboarding"],
    verdict: "Pelopor interoperabilitas dengan teknologi mendalam & pendiri kelas atas, tapi menghadapi tantangan adopsi parachain & erosi mindshare; nilainya bergantung revitalisasi ekosistem.",
    narratives: ["Layer-1", "Interop", "Parachain", "Multichain"],
  },
  {
    ticker: "POL", name: "POL (Polygon 2.0)", slug: "pol-pol", date: "2025-01-13",
    sectors: ["layer2", "infra", "layer1"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$3.7B", supply: "Circ 8B · Total 10B · Max ∞",
    extra: [{ label: "Sebelumnya", value: "MATIC (rebrand ke POL)" }],
    thesis: "Token native Polygon (dulu MATIC) untuk skalabilitas Ethereum berbiaya rendah, kini jadi token utama ekosistem multi-chain Polygon 2.0.",
    what: "Polygon (dulu Matic Network, 2017) adalah solusi scaling yang menurunkan gas & meningkatkan kecepatan di Ethereum. Desain modular & fleksibel. Migrasi MATIC → POL menjadikannya token Polygon 2.0 yang menyatukan banyak chain (termasuk AggLayer) untuk staking & keamanan bersama.",
    bull: ["Salah satu solusi scaling Ethereum paling teradopsi (banyak integrasi enterprise)", "Upgrade Polygon 2.0 + AggLayer menyatukan likuiditas lintas chain", "Biaya rendah & throughput tinggi menarik dApp konsumen & RWA", "Rebrand POL menambah utilitas (staking multi-chain)"],
    risks: ["Max supply tak terbatas (∞) via emisi POL", "Persaingan L2 sangat sengit (Arbitrum, Optimism, Base, zkSync)", "Kompleksitas transisi 2.0/AggLayer & risiko eksekusi", "Ketergantungan aktivitas Ethereum & retensi developer"],
    verdict: "Pemain scaling Ethereum mapan dengan visi multi-chain (2.0/AggLayer) ambisius; adopsi luas jadi kekuatan, tapi tekanan emisi tak terbatas & kompetisi L2 ketat membatasi upside.",
    narratives: ["Layer-2", "Scaling", "AggLayer", "Ethereum"],
  },
  {
    ticker: "ETC", name: "Ethereum Classic", slug: "ethereum-classic-etc", date: "2025-01-13",
    sectors: ["layer1"], category: "Altcoins Outlook · Layer-1",
    valuationAtReport: "$3.7B", supply: "Circ 150M · Total/Max 210M",
    extra: [{ label: "Konsensus", value: "Proof-of-Work (PoW)" }],
    thesis: "Blockchain PoW hasil fork ideologis Ethereum 2016 ('code is law'), dengan supply terbatas ala Bitcoin dan narasi immutability.",
    what: "Ethereum Classic lahir dari perpecahan komunitas Ethereum pasca peretasan The DAO 2016: ETC mempertahankan chain asli yang immutable alih-alih membalik transaksi. Tetap PoW setelah Ethereum pindah ke PoS, jadi salah satu chain smart-contract PoW terbesar. Max supply 210M (mirip Bitcoin).",
    bull: ["Supply terbatas (max 210M) → narasi kelangkaan mirip Bitcoin", "Salah satu jaringan smart-contract PoW terbesar pasca-Merge", "Sering jadi proksi/beta tinggi terhadap ETH & miner PoW", "Prinsip immutability menarik segmen anti-intervensi"],
    risks: ["Pengembangan & ekosistem dApp minim dibanding Ethereum", "Riwayat 51% attack → kelemahan keamanan PoW hash rendah", "Nilai sebagian besar spekulatif/korelasi ETH", "Model PoW kian kurang relevan & disorot isu energi"],
    verdict: "Aset dengan tesis kelangkaan + immutability dan korelasi tinggi ke ETH, namun ekosistem stagnan & risiko keamanan PoW membuatnya lebih spekulatif ketimbang fundamental.",
    narratives: ["Layer-1", "PoW", "Store of Value", "Immutability"],
  },
  {
    ticker: "MNT", name: "Mantle", slug: "mantle-mnt", date: "2025-01-11",
    sectors: ["layer2", "infra"], category: "Altcoins Outlook · Layer-2",
    valuationAtReport: "$3.9B", supply: "Circ 3.3B · Total/Max 6B",
    extra: [{ label: "Arsitektur", value: "Modular rollup (eksekusi/data/konsensus terpisah)" }],
    thesis: "Layer-2 Ethereum modular dengan pemisahan eksekusi–data–konsensus dan treasury besar, fokus skalabilitas plus interoperabilitas.",
    what: "Mantle adalah Layer-2 yang meningkatkan skalabilitas Ethereum sambil mewarisi keamanannya. Arsitektur modular rollup memisahkan eksekusi, ketersediaan data, dan konsensus — transaksi diproses off-chain lalu divalidasi di Ethereum. Didukung treasury ekosistem sangat besar (warisan BitDAO).",
    bull: ["Arsitektur modular (data availability terpisah) menekan biaya & menaikkan throughput", "Treasury/ekosistem sangat besar untuk insentif & pertumbuhan dApp", "Fokus interoperabilitas & produk native (staking/LST)", "Keamanan diwarisi dari Ethereum sebagai settlement layer"],
    risks: ["Persaingan L2 sangat padat (Arbitrum, Optimism, Base)", "Selisih circ vs total (3.3B→6B) → potensi tekanan unlock", "Adopsi organik pengguna/developer masih perlu dibuktikan", "Ketergantungan belanja treasury untuk mempertahankan aktivitas"],
    verdict: "L2 modular dengan amunisi treasury terbesar di kelasnya & desain teknis efisien; punya daya tahan pendanaan, tapi harus mengubah insentif jadi adopsi organik di tengah kompetisi L2 sengit.",
    narratives: ["Layer-2", "Modular", "Data Availability", "Ethereum"],
  },
  {
    ticker: "JASMY", name: "JasmyCoin", slug: "jasmycoin-jasmy", date: "2025-01-16",
    sectors: ["data", "depin", "infra"], category: "Altcoins Outlook · Data & IoT",
    valuationAtReport: "$1.5B", supply: "Circ 49B · Total/Max 50B (fully unlocked)",
    extra: [{ label: "Sharpe Ratio", value: "1.85" }],
    thesis: "Proyek asal Jepang yang menawarkan kepemilikan & monetisasi data pribadi secara terdesentralisasi lewat blockchain, menyasar ledakan data dari perangkat IoT.",
    what: "Ekosistem data terdesentralisasi bikinan Jasmy Corporation (Jepang), dijuluki 'Bitcoin of Japan'. Fitur inti Personal Data Locker (PDL) memberi user kontrol penuh atas datanya & opsi menjualnya via smart contract dengan bayaran JASMY. Fokus integrasi data IoT lintas industri.",
    bull: ["Narasi privasi & kedaulatan data makin relevan vs platform terpusat", "Supply sudah beredar penuh 50B → tidak ada tekanan unlock", "Positioning di pasar IoT global yang tumbuh eksponensial", "Legitimasi awal di Jepang sebagai proyek blockchain resmi"],
    risks: ["Adopsi nyata PDL & monetisasi data masih perlu dibuktikan skalanya", "Resistensi dari raksasa data terpusat yang mapan", "Utilitas token bergantung volume transaksi data aktual", "Upside murni bergantung pertumbuhan permintaan (supply penuh)"],
    verdict: "Salah satu proyek DePIN/data asal Asia dengan narasi privasi kuat & struktur supply bersih (tanpa unlock), tapi eksekusi adopsi PDL adalah kunci pembuktiannya.",
    narratives: ["DePIN", "Data Privacy", "IoT", "Asia"],
  },
  {
    ticker: "RENDER", name: "Render", slug: "render-render", date: "2025-01-16",
    sectors: ["depin", "ai", "infra"], category: "Altcoins Outlook · GPU Rendering",
    valuationAtReport: "$3.9B", supply: "Circ 517M · Total 532M · Max ∞",
    extra: [{ label: "Area scale-in", value: "$8 – $7 (weekly)" }],
    thesis: "Marketplace GPU terdesentralisasi yang menghubungkan kreator yang butuh rendering dengan pemilik GPU nganggur, menumpang narasi DePIN & lonjakan kebutuhan compute grafis/AI.",
    what: "Render Network mendemokratisasi akses rendering GPU: job rendering dikirim ke jaringan & didistribusikan ke penyedia GPU global yang dibayar token RENDER. Use case: animasi 3D, VFX film, simulasi real-time, arsitektur, metaverse. Salah satu proyek DePIN terbesar berdasarkan valuasi.",
    bull: ["Skalabilitas & efisiensi biaya rendering vs solusi terpusat", "Permintaan rendering naik dari game, film, metaverse", "Salah satu proyek DePIN paling besar & dikenal", "Pertumbuhan komunitas signifikan (Twitter 140rb→217rb)"],
    risks: ["Ketergantungan Ethereum → biaya tinggi saat jaringan padat", "Upside bergantung perluasan adopsi profesional kreatif", "Max supply tak terbatas (∞) → potensi inflasi", "Kapasitas jaringan harus mengejar kompleksitas permintaan"],
    verdict: "Leader DePIN untuk rendering GPU dengan use case nyata; saat report sedang koreksi, peluang scale-in di area $8-$7 bagi yang percaya tesis DePIN.",
    narratives: ["DePIN", "AI", "GPU Compute", "Metaverse"],
  },
  {
    ticker: "FLR", name: "Flare", slug: "flare-flr", date: "2025-01-12",
    sectors: ["layer1", "oracle", "interop"], category: "Altcoins Outlook · Data & Interoperability",
    valuationAtReport: "$1.3B", supply: "Circ 56M · Total 102M · Max ∞",
    extra: [{ label: "Sharpe 90h", value: "2.08 (Jan 2025)" }],
    thesis: "Layer-1 EVM yang fokus pada interoperabilitas & akses data off-chain aman lewat oracle asli, menjadikan data eksternal & aset non-smart-contract (mis. Bitcoin) bisa dipakai di DeFi.",
    what: "Blockchain Layer-1 dengan dua protokol inti: State Connector (verifikasi data dari chain lain & off-chain secara terdesentralisasi) dan Time Series Oracle/FTSO (data harga real-time). Kompatibel EVM, konsensus berbasis Avalanche, dan FAssets sebagai jembatan agar aset seperti Bitcoin bisa dipakai di Flare.",
    bull: ["Oracle terdesentralisasi bawaan mengurangi ketergantungan oracle terpusat", "Kompatibilitas EVM memudahkan migrasi developer Ethereum", "FAssets membuka likuiditas aset non-smart-contract (Bitcoin) ke DeFi", "Sharpe 90h 2.08 → performa risiko-imbal hasil solid"],
    risks: ["Kompetisi ketat di ceruk oracle (Chainlink) & interoperabilitas", "Max supply tak terbatas (∞) → potensi inflasi", "Adopsi developer & traksi dApps masih perlu tumbuh", "Utilitas FAssets bergantung keamanan mekanisme jembatan"],
    verdict: "Layer-1 data/oracle dengan pendekatan interoperabilitas unik; saat report harga retest area $0.02 yang dinilai zona beli ideal di weekly chart.",
    narratives: ["Layer-1", "Oracle", "Interoperability", "DeFi Data"],
  },
  {
    ticker: "ATOM", name: "Cosmos Hub", slug: "cosmos-hub-atom", date: "2025-01-12",
    sectors: ["layer1", "interop"], category: "Altcoins Outlook · Interoperability",
    valuationAtReport: "$2.5B", supply: "Circ 390M · Total 390M · Max ∞",
    extra: [{ label: "Area akumulasi", value: "$6 – $5.5 (weekly)" }],
    thesis: "Hub asli ekosistem Cosmos ('Internet of Blockchains') yang menghubungkan banyak blockchain independen via IBC dan menawarkan shared security lewat Interchain Security.",
    what: "Blockchain pertama di ekosistem Cosmos, berperan sebagai pusat interoperabilitas antar-'zone' via protokol IBC. Token ATOM untuk staking (PoS), governance, & keamanan jaringan. Interchain Security memungkinkan zone lain meminjam keamanan Cosmos Hub tanpa membangun validator sendiri.",
    bull: ["Pionir & salah satu jaringan interoperabilitas paling matang", "IBC menunjukkan pertumbuhan transfer lintas-blockchain signifikan", "Interchain Security memperluas utilitas ATOM (shared security)", "Pendekatan modular menarik banyak developer app-chain"],
    risks: ["Value capture ATOM dipertanyakan karena zone bisa mandiri", "Max supply tak terbatas (∞) dengan inflasi staking", "Persaingan interoperabilitas (Polkadot, LayerZero)", "Fragmentasi ekosistem app-chain mengurangi sentralitas Hub"],
    verdict: "Fondasi interoperabilitas matang dengan ekonomi staking kuat; saat report sedang koreksi dengan range $6-$5.5 sebagai area pembelian berkala.",
    narratives: ["Layer-1", "Interoperability", "Cosmos", "App-chain"],
  },
  {
    ticker: "OLAS", name: "Autonolas", slug: "autonolas-olas", date: "2025-01-07",
    sectors: ["ai", "infra"], category: "Altcoins Outlook · Autonomous Agents",
    valuationAtReport: "$128M", supply: "Circ 86M · Total 543M · Max ∞",
    thesis: "Infrastruktur untuk 'AI agents economy' — agen software otonom terdesentralisasi yang menjalankan layanan lintas DeFi, IoT, dan pengelolaan infrastruktur dengan sedikit intervensi manusia.",
    what: "Menggabungkan AI, DAO, dan layanan on-chain lewat Autonomous Service Organizations (ASOs): entitas digital berisi agen software cerdas yang beroperasi mandiri via smart contract. Agen mengelola data, layanan DeFi, infrastruktur, atau otomasi IoT dengan keputusan berbasis AI adaptif.",
    bull: ["Positioning awal di narasi AI agents yang naik daun", "Valuasi masih kecil ($128M) → ruang pertumbuhan besar", "Alokasi rewards dominan (47,4%) mendorong partisipasi", "Dukungan mitra ekosistem (Phala Network, Polywrap)"],
    risks: ["Kategori AI agents masih dini, adopsi nyata belum terbukti", "Konsentrasi alokasi DAO founding members (32,7%) tinggi", "Sirkulasi baru 86M dari total 543M → tekanan unlock", "Utilitas token bergantung volume layanan agen yang berjalan"],
    verdict: "Taruhan early-stage pada ekonomi agen AI dengan valuasi kecil; potensi tinggi jika narasi AI agents berlanjut, tapi berisiko & perlu dicermati jadwal unlock-nya.",
    narratives: ["AI", "AI Agents", "Autonomous", "DAO"],
  },
  {
    ticker: "PHA", name: "Phala", slug: "phala-pha", date: "2025-01-07",
    sectors: ["ai", "infra", "depin"], category: "Altcoins Outlook · Privacy Compute",
    valuationAtReport: "$271M", supply: "Circ 777M · Total/Max 1B",
    extra: [{ label: "Eksekusi kontrak", value: "+107% YoY" }],
    thesis: "Cloud compute terdesentralisasi berbasis privasi (TEE) di atas Polkadot, memposisikan diri sebagai infrastruktur eksekusi untuk AI agents dengan kerahasiaan data.",
    what: "Platform blockchain berbasis privasi memakai Trusted Execution Environment (TEE) — hardware terisolasi — agar smart contract dieksekusi tanpa datanya terlihat pihak ketiga (termasuk node). Dibangun di atas Polkadot dengan desain dual-node. Pemrosesan off-chain via TEE menambah skalabilitas. PHA untuk bayar layanan, insentif node, governance.",
    bull: ["Transparansi blockchain + privasi data cocok untuk data sensitif", "Eksekusi kontrak +107% YoY → permintaan nyata naik", "Adopsi AI Agents Contract tren eksponensial", "Supply hampir fully diluted (777M dari 1B) → minim kejutan unlock"],
    risks: ["Ketergantungan hardware TEE → risiko keamanan/kepercayaan vendor", "Sedikit pelemahan kuartalan (-3% QoQ) pada eksekusi kontrak", "Persaingan privacy compute & AI infra makin ramai", "Bergantung keberlanjutan momentum narasi AI"],
    verdict: "Infrastruktur privacy compute dengan traksi eksekusi kontrak bertumbuh & bertaut ke narasi AI agents; menarik jika tren AI berlanjut.",
    narratives: ["AI", "Privacy", "Compute", "DePIN", "AI Agents"],
  },
  {
    ticker: "PLUME", name: "Plume", slug: "plume-plume", date: "2025-02-06",
    sectors: ["rwa", "layer1", "defi"], category: "Altcoins Outlook · Modular RWA",
    valuationAtReport: "$262M", supply: "Circ 2B · Total/Max 10B",
    extra: [
      { label: "Traksi", value: "180+ protokol · 18jt+ address · 3jt+ user" },
      { label: "Pendanaan", value: "Seri A $20M (Brevan Howard, Haun, Galaxy)" },
    ],
    thesis: "Layer-1 modular yang dikhususkan untuk RWAfi — menyederhanakan tokenisasi aset dunia nyata & mengintegrasikannya ke DeFi, menunggangi narasi RWA yang didukung smart money.",
    what: "Blockchain Layer-1 modular khusus Real World Assets: memudahkan tokenisasi aset dunia nyata, distribusi global, & pemanfaatannya di DeFi. Ekosistem mencakup komoditas, NFT, stablecoin RWA, & infrastruktur keuangan. Dilengkapi mekanisme compliance tanpa mengorbankan UX/desentralisasi.",
    bull: ["Narasi RWA paling hot & didukung investor institusional (smart money)", "Traksi awal kuat: 180+ protokol, 18jt+ address, 3jt+ user", "Backing kelas atas (Brevan Howard, Galaxy, Haun) + $25M ecosystem fund", "Fokus vertikal RWAfi sebagai diferensiasi vs L1 generalis"],
    risks: ["Sirkulasi baru 2B dari 10B → tekanan unlock besar", "Tokenisasi RWA menghadapi hambatan regulasi lintas yurisdiksi", "Proyek baru, chart masih konsolidasi volatil", "Kompetisi RWA memanas (Ondo, Centrifuge)"],
    verdict: "Pure-play RWA Layer-1 dengan traksi awal & backing kuat pada valuasi relatif rendah; pola konsolidasi khas new listing → strategi multiple entry (cicil) dinilai cocok.",
    narratives: ["RWA", "RWAfi", "Layer-1", "Institutional"],
  },
];

/** Newest-first. */
export function researchSorted(): ResearchCard[] {
  return [...RESEARCH].sort((a, b) => (a.date < b.date ? 1 : -1));
}
